### ISSUE TITLE
Change Sync logo colors to match Lemmy

### ISSUE THREAD

**Issue by Semperverus** [laurencedawson/sync-for-lemmy#1]
**Describe the bug**  
Sync has orange up arrow and blue down arrow. Lemmy has blue upvotes and orange downvotes.

**Steps to Reproduce**  
1. Go to Sync logo
2. Look at Sync logo
3. See that it is upside down

**Expected behavior**  
Blue arrow should be on top, orange on bottom.
Rotate 180° to fix.

**Comment by laurencedawson** [comment]
The latest update added this!
