### ISSUE TITLE
Sync for Lemmy Sign in - 'Username' field doesn't accept underscore character

### ISSUE THREAD

**Issue by dohlin** [laurencedawson/sync-for-lemmy#10]
**Describe the bug**  
Add account login "Username" field does not accept the underscore (_) character.  This is problematic lol :)

**Steps to Reproduce**  
1. Go to the sidebar (or drawer)
2. Click on 'Add account'
3. Click into the "Username" field and try entering a username including the "_" character
4. No _'s are actually typed into the field

**Expected behavior**  
Field should accept the underscore character as valid

**Screenshots**  
Hopefully is pretty clear, can add screenshots if needed

**Smartphone (please complete the following information):**
 - Device: Samsung S22 Ultra
 - Android: 13
 - Sync version: Lemmy Beta

**Comment by laurencedawson** [comment]
Fixed
