### ISSUE TITLE
Reporting a post displays a "Post Reported" toast message, but no report is received by the mod.

### ISSUE THREAD

**Issue by kringger** [laurencedawson/sync-for-lemmy#100]
**Describe the bug**  

Reporting a post displays a "Post Reported" toast message, but no report is received by the mod.

**Steps to Reproduce**  
1. Go to a post
2. Click on '3-dot' menu
3. Click 'report'
4. Put in a reason and submit
5. See toast saying "post reported"
6. Report is never received by the mod

**Expected behavior**  
The report should be submitted. Alternatively if reporting is a feature coming later, update the toast message to say "coming soon"

**Screenshots**  
![Screenshot_20230725-183736_1.png](https://github.com/laurencedawson/sync-for-lemmy/assets/35173157/bfcbc91a-6e9b-4f89-9773-e55631e242b6)

**Smartphone (please complete the following information):**
 - Device: pixel 6 pro
 - Android: 13
 - Sync version: beta 12
 - Sync variant: beta 12

**Additional context**  
None

**Comment by laurencedawson** [comment]
Fixed.
