### ISSUE TITLE
Remove Flair Stuff

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#101]
**Describe the bug**  
For now, flair isn't available on lemmy at all, so all references should probably be hidden or removed

**Steps to Reproduce**  
1. Go to post Settings 
2. Click on Post Options
3. Scroll down to Flair section

**Expected behavior**  
Shouldn't be there

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: [e.g. v22.5.20]
 - Sync variant: [e.g. pro]

**Additional context**

**Comment by pwd-github** [comment]
Post Flair: https://github.com/LemmyNet/lemmy/issues/317

User Flair: https://github.com/LemmyNet/lemmy/issues/1456

**Comment by laurencedawson** [comment]
So if I'm reading this right Lemmy isn't planning to add these?

**Comment by pwd-github** [comment]
Not any time soon.

**Comment by laurencedawson** [comment]
Dang.

Fixed, thanks for the report.
