### ISSUE TITLE
Explore Sheet Issues: No "moderates/moderator" category in explore sheet, favoriting an community removes it from its original category instead of copying it, and unable to change order of categories.

### ISSUE THREAD

**Issue by kringger** [laurencedawson/sync-for-lemmy#103]
**Describe the bug**  
Title

**Steps to Reproduce**  
1. Go to 'exolore' tab
2. See that there is no moderator category despite being a moderator for a community 
3. Favorite a community 
4. See that it is removed from feeds or subscriptions and placed in favorites
5. Attempt to change category order (i.e. have feeds first, then favorites, then subscriptions)
6. You can't reorganize categories

**Expected behavior**  
1. A moderator category should exist for communities you moderate
2. Adding a community to favorites should copy it to the favorites category and not remove it from feeds or subscriptions (or moderates)
3. You should be able to reorganize the categories to be a custom order just like you can with communities. (feeds, subscriptions, favorites, moderates)

**Screenshots**  
![Screenshot_20230725-192056.png](https://github.com/laurencedawson/sync-for-lemmy/assets/35173157/ecec88f7-12cf-4d8e-8927-6ab8ade4100d)

**Smartphone (please complete the following information):**
 - Device: pixel 6 pro
 - Android: 13
 - Sync version: beta 12
 - Sync variant: beta 12

**Additional context**  
This is a 3-in-one but they all pertain to the explore sheet organization. Let me know if I should break these out separately.

**Comment by pwd-github** [comment]
1 is fixed in beta 13
2 is an option, duplicate favourites
3 seems a new issue

**Comment by kringger** [comment]
Thanks, somehow I missed #2. Much appreciated

**Comment by laurencedawson** [comment]
No plans to allow rearranging of categories.

1 & 2 are already fixed.
