### ISSUE TITLE
Unable to share direct image on Android 14 Beta

### ISSUE THREAD

**Issue by beerbaronstatic** [laurencedawson/sync-for-lemmy#104]
**Describe the bug**  
Clicking on "direct" when trying to share an image does nothing

**Steps to Reproduce**  
1. Go to any image
2. Click on share
3. Choose 'Direct'
4. Share menu closes with no further action

**Expected behavior**  
Android share sheet should show to choose where to share the image

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - Android: 14 Beta 4
 - Sync version: Lemmy Beta 12

**Comment by laurencedawson** [comment]
Will be closed when #37 is completed.

**Comment by laurencedawson** [comment]
Done.

**Comment by laurencedawson** [comment]
Fixed again.
