### ISSUE TITLE
Replace hardcoded orange

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#106]
**Describe the bug**  
There's a bunch of hardcoded orange in the app which was I guess to make it feel more like a Reddit app. But since this is Sync for Lemmy, how about replacing it with blue or even having it use the Monet accent. 

**Steps to Reproduce**  
1. Go to your default feed
2. Click on upvote 
3. Orange

**Expected behavior**  
Blue for up, orange for down or just Monet accent colour. 

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - Android: 13
 - Sync version: beta 12
 - Sync variant: internal

**Additional context**

**Comment by laurencedawson** [comment]
This has been added for the latest release.
