### ISSUE TITLE
Subscribing to C# causes a hard crash

### ISSUE THREAD

**Issue by laurencedawson** [laurencedawson/sync-for-lemmy#108]

**Comment by xaeraorg** [comment]
Even just visiting the specific community causes Sync to not boot past the splash screen and requires a full data clear of the app

**Comment by garpunkal** [comment]
I had to clear data to stop this from crashing my sync. 

Then restore all accounts. :(

**Comment by xaeraorg** [comment]
That's why I decided to put the warning in, because I knew people might try it out

**Comment by laurencedawson** [comment]
Fixed for the next release.
