### ISSUE TITLE
Portrait 2 columns layout bug

### ISSUE THREAD

**Issue by garpunkal** [laurencedawson/sync-for-lemmy#11]
**Describe the bug**  
Text is wrapping tightly 

![Screenshot_20230724-220521.png](https://github.com/laurencedawson/sync-for-lemmy/assets/13114807/1979d455-2e84-4ac2-9df5-085f4f1a9944)

Pixel 7. Android 14beta 4

**Comment by garpunkal** [comment]
Please fix this for lemmy. It seems worse because of the amount of links shared.  I love this view for viewing content.

**Comment by laurencedawson** [comment]
Nooo this issue followed me...

**Comment by garpunkal** [comment]
I think it feels worse as there are so many links being shared now.

**Comment by laurencedawson** [comment]
Added a fix for the next release.
