### ISSUE TITLE
Crash when Biometric account lock is enabled

### ISSUE THREAD

**Issue by Antik79** [laurencedawson/sync-for-lemmy#110]
**Describe the bug**  
The app crashes/closes when you have an account added and you enabled Biometric account lock.  You won't be able to re-open the app anymore without crashing either.  App data needs to be removed to resolve.

**Steps to Reproduce**  
1. Add an account
2. Enable "Biometric account lock"
3. Close the app completely
4. Restart Sync

**Expected behavior**  
Biometric lock prompt and then continue to the application. 

**Screenshots**  
None

**Smartphone (please complete the following information):**
 - Device: Samsung FE 21
 - Android: 13
 - Sync version: 23.07.25-16:32
 - Sync variant: Test

**Additional context**  
None

**Comment by NomNuggetNom** [comment]
No problems for me.

 - Device: OnePlus 7 Pro
 - Android: 13
 - Sync version: v23.07.24-19:15 (5)
 - Sync variant: Lemmy

**Comment by laurencedawson** [comment]
Unable to reproduce this. 

If anyone else can please let me know.

**Comment by Antik79** [comment]
It doesn't crash anymore. Neither for startup or account switching

Op di 1 aug. 2023 01:11 schreef Laurence Dawson ***@***.***>:

**Comment by laurencedawson** [comment]
Thanks for the follow up.
