### ISSUE TITLE
Import / Export Subscribed Communities

### ISSUE THREAD

**Issue by garpunkal** [laurencedawson/sync-for-lemmy#111]
- The ability to export subscribed communities into a JSON file 
- The ability to import subscribed communities in from a JSON File. 
    - This will subscribe you to communities upon import for the logged in account.

**Comment by laurencedawson** [comment]
Will be part of Ultra. Added to the Ultra milestone.

**Comment by brad-anderson** [comment]
I think making this an automatic thing where you can specify the backup accounts of your "main" account and it automatically subscribes to whatever is missing periodically would be really nice.

**Comment by laurencedawson** [comment]
Added for the next release. Thanks for the idea @garpunkal!
