### ISSUE TITLE
Sorting comments by top causes bugs and a crash.

### ISSUE THREAD

**Issue by Alluminy** [laurencedawson/sync-for-lemmy#113]
Description:
If you sort the comments of a post by top, the post and comment UI will become glitched. If you scroll down too far in this state, the application will crash.

Reproduction:
1. Go to any post
2. Change comment sort to top
3. Scroll down until the application crashes

Video:
https://github.com/laurencedawson/sync-for-lemmy/assets/65433821/96a8364f-0eaf-4eb5-aa87-dd910d512d8e

Device information:
 - Device: Pixel 6 Pro
 - Android: 13
 - Sync version: v23.07.25-16:32 // Beta 12 of S4L

**Comment by laurencedawson** [comment]
Fixed.
