### ISSUE TITLE
Tapping "Everything" at the top causes an immediate crash

### ISSUE THREAD

**Issue by brad-anderson** [laurencedawson/sync-for-lemmy#115]
**Describe the bug**  
Tapping "Everything" at the top to switch to Local or Subscribed causes Sync to crash

**Steps to Reproduce**  
1. Tap "Everything"
2. Crash

**Expected behavior**  
Normally has a list to select a different feed pops up.

**Screenshots**  
N/A

**Smartphone (please complete the following information):**
 - Device: Samsung S21 Ultra
 - Android: 13
 - Sync version: v23.07.26-22:51 (Beta 13)
 - Sync variant: Internal

**Additional context**  
Clearing App Data did not fix the issue. It happens on any account, including Anonymous.

**Comment by corylowry12** [comment]
Am able to replicate. Happens every time.

**Comment by brad-anderson** [comment]
Fixed with Beta 14

**Comment by brad-anderson** [comment]
Fixed
