### ISSUE TITLE
Typo in the settings 

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#116]
When searching in the settings for something that's under "Comment options" it shows up as "Commentlist"
![Screenshot_20230726_191442_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/8837361/39d21e16-a66e-4b86-9083-23b4fec5b6e3)
![Screenshot_20230726_191436_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/8837361/8bd2ecde-20cd-4b74-bb2f-cc0737e2b81c)

**Comment by laurencedawson** [comment]
Fixed cheers.
