### ISSUE TITLE
User domain not shown in posts for accounts with a custom name

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-lemmy#118]
**Describe the bug**  

If a user has a custom name set, the domain is hidden on the user's post even if the account is not from the current instance.

**Steps to Reproduce**  
1. Go to https://lemmy.world/post/2198717
2. See error

**Expected behavior**  

The domain should still show, but since it is currently formatted as `username@domain` it may require a separate way to show user names entirely.

**Screenshots**  

<img src="https://github.com/laurencedawson/sync-for-lemmy/assets/13911156/4cd7c4f5-3faf-4e02-903e-fc0d92526dc2" width=250 />

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - Android: 10
 - Sync version: v23.07.27-01:13 (14)
 - Sync variant: Beta

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
