### ISSUE TITLE
"View Parent" displays wrong thread

### ISSUE THREAD

**Issue by toolCHAINZ** [laurencedawson/sync-for-lemmy#119]
**Describe the bug**  
The "view parent..." button when viewing a single comment loads the wrong comment thread/post.

**Steps to Reproduce**  
1. Navigate to any profile page.
2. Navigate to "Comments"
3. Click a comment that is not a top-level comment (so, in reply to something).
4. Sync will open a fullscreen view of that comment (and presumably its descendents), with a placeholder for the parent that says "view parent..."
5. Clicking "view parent..." will navigate you to some other thread (it seems to deterministically be the same incorrect thread, and is different per comment).

**Expected behavior**  
View parent should open the parent to the comment I'm viewing.

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - Android: 13
 - Sync version: Beta 14

**Comment by chloyster** [comment]
Was just coming here to report this. On beta 14. 

Have a video of it here
https://github.com/laurencedawson/sync-for-lemmy/assets/15004447/86866a7e-96ac-423f-acdb-67482bab2f44

**Comment by toolCHAINZ** [comment]
Playing with beta 18, it looks like this got fixed.
