### ISSUE TITLE
Image open comments doesn't work. 

### ISSUE THREAD

**Issue by garpunkal** [laurencedawson/sync-for-lemmy#12]
![Screenshot_20230724-221053.png](https://github.com/laurencedawson/sync-for-lemmy/assets/13114807/7d4b059d-675d-4846-b9aa-b93707c0161a)

Clicking on comments tries to open Reddit link

**Comment by Kurocon** [comment]
Reproduction instructions:

1. Open an image
2. Swipe up to show the detail view at the bottom
3. Press the comment button on the left
4. Error like the one below pops up :
![image](https://github.com/laurencedawson/sync-for-lemmy/assets/1193988/0e602881-f542-4175-a090-f7b8a7642aac)

**Comment by laurencedawson** [comment]
Good spot
