### ISSUE TITLE
Resolving domains is incredibly slow

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#121]
**Describe the bug**  
Need to speed up the resolving of internal links

**Steps to Reproduce**  
1. Go to the new communities community
2. Click on a post 
3. Press any exclamation link

**Expected behavior**  
Resolving should be nearly instantaneous, for some reason it's not. Probably need to profile this to find out where the delay is coming from as it makes 13 feel a lot slower than 12

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - Android: 13
 - Sync version: beta 13
 - Sync variant: beta 

**Additional context**

**Comment by pwd-github** [comment]
I think part of the problem is that sync is trying to figure out if a URL is a lemmy instance of not. If so #77 could help. As you'll already have the top XX instances cached and so won't need to wait for a response, you can just start processing.

**Comment by laurencedawson** [comment]
Previous versions didn't support resolving links at all so it can't have felt faster lol.

If a link is internal the process should be fast, do you have any examples where the process is slow?

**Comment by pwd-github** [comment]
It's much faster today, but if you press [this link](https://lemmy.world/post/2216085) and press a couple communities on difference instances (preferably ones you're not federated with, you should see what I'm referring to

**Comment by laurencedawson** [comment]
Its almost instant for me.

**Comment by laurencedawson** [comment]
Closing as this has improved significantly over time.
