### ISSUE TITLE
Comments Section in settings is titled CommentList

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#123]
**Describe the bug**  
Seems to be missing the correct string for the title of the settings -> comments section

**Steps to Reproduce**  
1. Go to Settings
2. Click on Comments
3. See error

**Expected behavior**  
Should just say Comments 

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - Android: 13
 - Sync version: beta 14
 - Sync variant: beta

**Additional context**

**Comment by laurencedawson** [comment]
Fixed cheers
