### ISSUE TITLE
Pressing title of a post in your comment history attempts to open a Reddit link

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#124]
**Describe the bug**  
When attempting to open a thread in your comment history by pressing the title, Sync attempts to open a Reddit link

**Steps to Reproduce**  
1. Go to your profile
2. Click on the dropdown to switch to comments
3. Press a title

**Expected behavior**  
Thread should open

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - Android: 13
 - Sync version: beta 14
 - Sync variant: beta 

**Additional context**

**Comment by laurencedawson** [comment]
Fixed.
