### ISSUE TITLE
Selectively hide NSFW previews not working when turned on

### ISSUE THREAD

**Issue by Mwj341** [laurencedawson/sync-for-lemmy#129]
**Describe the bug**  
After updating to beta 14, the red box to hide NSFW content while scrolling has stopped working even with the setting checked. It was working on previous releases. 

**Steps to Reproduce**  
1. Go to everything
2. Scroll down until NSFW content is showed
3. See boobies

**Expected behavior**  
NSFW posts should be masked with a red box with the selectively hide setting enabled. 

**Screenshots**  
I'll leave this one blank ;) 

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro 
 - Android: 13
 - Sync version: v23.07.27-01:13
 - Sync variant: beta 14

**Additional context**  
Not the worst bug to encounter in the morning

**Comment by laurencedawson** [comment]
Got it. Cheers
