### ISSUE TITLE
expanded comment options not closing

### ISSUE THREAD

**Issue by Phuntis** [laurencedawson/sync-for-lemmy#131]
the expanded options on a comment used to close when you pressed something like you press the comment to open them press upvote and it immediately closes but it's not anymore it stays open I tried closing the app and clearing the cache just in case but that didn't fix it nugget says it isn't happening for them so it must be inconsistent so I unfortunately don't know how to reproduce sorry

**Comment by laurencedawson** [comment]
Fixed.
