### ISSUE TITLE
View more button not working properly

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#132]
**Describe the bug**  

**Steps to Reproduce**  
1. Go to a post
2. Scroll down until you see a view more button
3. Click on it

**Expected behavior**  

- it to load the hidden comment

**Screenshots**  

![Screenshot_20230727_104413_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/8837361/83c4da46-680d-4cb1-a27a-2dff66a707b1)

![Screenshot_20230727_104419_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/8837361/a2900543-6ead-4e85-aa84-2288423ca308)

**Comment by laurencedawson** [comment]
I can only reproduce this using the top sort. There seems to be some strange stuff happening with top sort.

**Comment by corylowry12** [comment]
Yeah, it was sorted using top
