### ISSUE TITLE
Malformed comment view, crash upon clicking More actions when viewing a post

### ISSUE THREAD

**Issue by Alluminy** [laurencedawson/sync-for-lemmy#134]
Description:
There are issues when representing comment trees. An example is shown in the video. 
Crash upon trying to click More actions while in post view. This does not happen while viewing a feed (community, user).

Reproduction:
1. Open a post
2. Click More actions (three dots button at top-right)
Note: I am unsure of why the comment tree appears as such in the video.

Example:
https://github.com/laurencedawson/sync-for-lemmy/assets/65433821/76fca4e8-151a-4db8-b13c-aecfa8c0d5a9

Device information:
 - Device: Pixel 6 Pro
 - Android: 13
 - Sync version: v23.07.27-13:47 // Beta 18 of S4L

Logcat:
[logcat.txt](https://github.com/laurencedawson/sync-for-lemmy/files/12195879/logcat.txt)

**Comment by corylowry12** [comment]
Unable to replicate

**Comment by Alluminy** [comment]
Here is a crash log of the issue:
[logcat.txt](https://github.com/laurencedawson/sync-for-lemmy/files/12195879/logcat.txt)

**Comment by laurencedawson** [comment]
Unable to reproduce this.

**Comment by Alluminy** [comment]
Issue has been resolved upon resetting app data.
