### ISSUE TITLE
Community Posts Moderator Function

### ISSUE THREAD

**Issue by mikeyd85** [laurencedawson/sync-for-lemmy#137]
Please allow moderators to pin and unpin Community posts.

Pin / Unpin to appear in the "Post Options" menu.

Same as this function in the web UI:

![image](https://github.com/laurencedawson/sync-for-lemmy/assets/64745331/044aa5a1-7dac-4cf4-846d-0fa2350596ba)

**Comment by laurencedawson** [comment]
This was added in today's release.
