### ISSUE TITLE
App resets scroll position in theme management when changing between "Automatic" and "Manual selection"

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#139]
**Describe the bug**  

The app resets scroll position when switching between automatic and manual theming

**Steps to Reproduce**  
1. Go to settings
2. Click on theme management
3. Scroll down a little
4. Swap between manual or automatic
5. The scroll position will be reset

**Expected behavior**  

- The app to remember scroll position

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: [e.g. v22.5.20]
 - Sync variant: [e.g. pro]

**Comment by laurencedawson** [comment]
The options are different so this is intentional.
