### ISSUE TITLE
Switch color is wrong when swapping between theming settings 

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#140]
Go to theme management, swap between colors and colorful light mode and sometimes the switches will not swap back or to the new color. It's fairly inconsistent but was able to make it happen a couple times. The top switch in the screenshot is one that done it. The first time it was the two below it. 

![Screenshot_20230727_195921_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/8837361/5fbb46c1-fbcc-41ce-9c62-b2a6cacec411)

**Comment by corylowry12** [comment]
This seems to be much worse after the latest update, does it pretty much every time you swap between themes now

**Comment by laurencedawson** [comment]
Fixed for the next release.
