### ISSUE TITLE
Standardize terminologies to user membership status

### ISSUE THREAD

**Issue by brunelli** [laurencedawson/sync-for-lemmy#141]
**Describe the bug**  
Following Lemmy's web UI terminologies, the user membership status to a community should have a concise name throughout Sync's interface.

**Steps to Reproduce**  
1. Go to **Explore**
2. See the subscribed communities under the subtitle **Subscriptions**
3. Click the three dot menu on the side of a community
4. See an **Unsubscribe** option
5. Open the community
6. See the label for subscribed is **Joined**
7. Click **Joined**
8. See the label for unsubscribe is **Remove**

**Expected behavior**  
I expect the words subscription/subscribe/subscribed/unsubscribe to be always used when referring to a user membership status to a community.

**Smartphone (please complete the following information):**
 - Device: S22 Ultra
 - Android: 13
 - Sync version: v23.07.28-01:03 (Beta 19)
 - Sync variant: Beta

**Comment by laurencedawson** [comment]
Join chips have been renamed
