### ISSUE TITLE
Open text post in browser does nothing

### ISSUE THREAD

**Issue by Ictinus** [laurencedawson/sync-for-lemmy#142]
**Describe the bug**  
Choosing to open a text only post in browser does not open anything.

**Steps to Reproduce**  
1. Go to a text post ( not containing an image )
2. Click on Post Options -> Open in browser
3. See that no browser is opened.

**Expected behavior**  
The text post should open in a browser.

**Device information**

    Sync version: v23.07.28-01:03  beta 19
    Sync flavor: googlePlay    
    
    View type: Slides    
    Push enabled: false    
    
    Device: oriole    
    Model: Google Pixel 6    
    Android: 13

**Additional context**  
This occurs if actioned from the community or from an opened post.
If the past contained an image the image is opened in a browser successfully.

**Comment by corylowry12** [comment]
Same here

**Comment by laurencedawson** [comment]
Fixed.
