### ISSUE TITLE
Clicking on the upper sort icon causes sync to crash

### ISSUE THREAD

**Issue by Nerdulous** [laurencedawson/sync-for-lemmy#143]
**Describe the bug**  
Clicking on the sort icon (three horizontal bars) in the upper left causes the app to hang and then crash. 

**Steps to Reproduce**  
1. Open app
2. Click on sort button
3. Crash

**Expected behavior**  
I expected the sort options dialog to appear.

**Smartphone (please complete the following information):**
 - Device: Pixel 6 pro
 - Android: Android 14 beta 4.1
 - Sync version: beta 19
 - Sync variant: beta

**Additional context**

**Comment by corylowry12** [comment]
Unable to replicate

**Comment by garpunkal** [comment]
It closes the app for me

**Comment by laurencedawson** [comment]
Does this happen on beta 21?

**Comment by Nerdulous** [comment]
I just updated to beta 22 and it still occurs on my device

**Comment by laurencedawson** [comment]
Looks like an Android 14 issue and duplicate of:

https://github.com/laurencedawson/sync-for-lemmy/issues/6

The other reporter noted:

> I found out it only crashes when the Developer Options toggle 'Transparent navigation bar' (Introduced in Android 14) is enabled and when a sheet opens from the top.

Might be worth checking this.

Closing duplicate issue.
