### ISSUE TITLE
Block option is visible on your own profile 

### ISSUE THREAD

**Issue by Vlixz** [laurencedawson/sync-for-lemmy#144]
**Describe the bug**  
The option to block a user is visible on your own profile.

**Steps to Reproduce**  
1. Go to your profile.
2. See block option.

**Expected behavior**  
The block option is hidden on your own profile.

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord
 - Android: Andriod 11
 - Sync version: v23-07-28
 - Sync variant: Lemmy

**Comment by laurencedawson** [comment]
Fixed.
