### ISSUE TITLE
Autoplay for inline GIFs doesn't work (only in comments?)

### ISSUE THREAD

**Issue by kontrastylez** [laurencedawson/sync-for-lemmy#147]
**Steps to Reproduce**  
1. Go to https://lemmy.world/comment/1820663
2. See GIF not autoplaying

**Expected behavior**  
GIF should autoplay

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - Android: 13
 - Sync version: v23.07.28-01:03

**Comment by laurencedawson** [comment]
Fixed!
