### ISSUE TITLE
Sharing to Sync link handler gives a [TODO deeplink] toast message

### ISSUE THREAD

**Issue by Nictadel** [laurencedawson/sync-for-lemmy#149]
**Description**  
Sharing something to the Sync Link Handler in the android share sheet has missing functionality, currently opens the app and shows a toast message "TODO deeplink"

**Steps to Reproduce**  
1. Go to a link that sync should be able to open (eg: https://lemmy.world/c/syncforlemmy)
3. Share it via _Sync link handler_
4. App opens and shows toast message

**Expected behavior**  
Sync tries to resolve the link and opens it if possible (posts, users, communities,...)

**Screenshots**  
![image](https://github.com/laurencedawson/sync-for-lemmy/assets/17566036/f6af246d-6742-4c3f-bf96-f51f138508d5)

**Smartphone:**
 - Device: Pixel 7 Pro
 - Android: 13
 - Sync version: Beta 19

**Additional context**  
Didn't see this TODO mentioned in the issues, better safe than sorry 😄

**Comment by laurencedawson** [comment]
This was fixed in beta 34.
