### ISSUE TITLE
Android Notification channels still mention Sync for Reddit

### ISSUE THREAD

**Issue by Nictadel** [laurencedawson/sync-for-lemmy#15]
**Describe the bug**  
In the android menu to manage notifications for the app, the different notification channels still mention Sync for Reddit instead of Sync for Lemmy

**Steps to Reproduce**  
1. Long Press app icon in drawer/homescreen
2. Tap "App Info"
3. Tap Notifications
4. Enable notifications (if disabled)

**Expected behavior**  
Notifications channels shouldn't mention Reddit

**Screenshots**  
![Screenshot_20230724-230635](https://github.com/laurencedawson/sync-for-lemmy/assets/17566036/e1724a4a-ea1e-4b92-b427-9abc8b1c7baa)

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - Android: 13
 - Sync version: 23.07.23-19:51

**Comment by laurencedawson** [comment]
Fixed, cheers!
