### ISSUE TITLE
Downloading media doesn't show a notification in the notification tray

### ISSUE THREAD

**Issue by kringger** [laurencedawson/sync-for-lemmy#150]
**Describe the bug**  
Title

**Steps to Reproduce**  
1. Go to 'https://kbin.social/m/memes@sopuli.xyz/t/264754'
2. Click on image
3. Click download button
4. See toast message saying 'downloading media'
5. Media downloads but there is no notification in the notification tray

**Expected behavior**  
Media should show as downloaded in the notification tray

**Screenshots**  
None

**Smartphone (please complete the following information):**
 - Device: pixel 6 pro
 - Android: 13
 - Sync version: beta 19
 - Sync variant: beta 19

**Additional context**  
None

**Comment by kringger** [comment]
Correction, downloading works but there is no indication other than the toast message. I would expect this to show in the notification shade.

I do have Download manager set to allow notifications

![Screenshot_20230729-172347.png](https://github.com/laurencedawson/sync-for-lemmy/assets/35173157/2141137b-4175-4e4f-a01d-3357b6db3622)

I will update the issue title and description

**Comment by corylowry12** [comment]
It does for me. Maybe notifications for Sync are set to disabled?

**Comment by kringger** [comment]
Yes, it turns out this was related to the bug with sync notifications defaulting to off. I'll close this now
