### ISSUE TITLE
Unsubscribe action fails silently 

### ISSUE THREAD

**Issue by ctking425** [laurencedawson/sync-for-lemmy#151]
**Describe the bug**  
When an instance has degraded performance or is down, if I unsubscribe from a community in that instance it will appear to be successful until reloaded.

**Steps to Reproduce**  
1. Instance having performance issues (lemmy.world cough cough)
2. Open explore panel and unsubscribe from a community.
3. Community is removed from list with no indication of error.
4. Switch accounts to another instance
5. Switch back to troubled instance
6. Open explore panel and see unexpected community 

**Expected behavior**  
I'd the action to unsubscribe fails with an instance I would expect the error to be displayed and the community to remain in the list.

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - Android: 13
 - Sync version: Beta 19 23.07.28-1:03

**Comment by laurencedawson** [comment]
Fixed for the next release.
