### ISSUE TITLE
Copy username doesn't include instance

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#156]
**Describe the bug**  
When clicking on a post and then pressing copy username, it doesn't include the instance

**Steps to Reproduce**  
1. Go to a post or reply
2. Click on copy
3. Scroll down to username

**Expected behavior**  
You should get ljdawson@instance.tld

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: [e.g. v22.5.20]
 - Sync variant: [e.g. pro]

**Additional context**

**Comment by laurencedawson** [comment]
Added.
