### ISSUE TITLE
Sync still thinks karma is a thing

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#158]
**Describe the bug**  
I believe this will be solved by #28 , but just in case I'm filing a bug. If you press a profile and the press about, it shows points, but karma isn't a thing on lemmy so it's probably best to remove it. 

**Steps to Reproduce**  
1. Go to your profile
2. Click on about
3. See error

**Expected behavior**  
You don't see points. 

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - Android: 13
 - Sync version: beta 19
 - Sync variant: internal

**Additional context**

**Comment by laurencedawson** [comment]
Should I just remove this? What should be there instead?

**Comment by pwd-github** [comment]
Replace it with Posts and Comments. That's what the web does and that should be enough.

**Comment by laurencedawson** [comment]
Fixed.
