### ISSUE TITLE
Profile "error" (no comments etc) stay visible 

### ISSUE THREAD

**Issue by Vlixz** [laurencedawson/sync-for-lemmy#16]
**Describe the bug**  
Hopefully this is not intentional, but when viewing a profile without posts the "This user has no post" message stays visible.

**Steps to Reproduce**  
1. Go to a users profile which doesn't have posts.
2. Message doesn't go away.

**Expected behavior**  
Message disapears after a couple seconds, or is able to be swiped to dismiss.

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord 
 - Android: Andriod 11
 - Sync version: v23.07.24
 - Sync variant: Lemmy

**Additional context**  
This issue also exist with "No most posts are loaded" message in the users comments/saved posts/saved comment's

**Comment by laurencedawson** [comment]
You can swipe to dismiss it.
