### ISSUE TITLE
Switch Media Upload Dialog for Bottom Sheet 

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#160]
**Describe the bug**  
The current dialog doesn't match the rest of the app. It looks kinda stuck in there

**Steps to Reproduce**  
1. Go to a post
2. Click on reply
3. Press image
4. See dialog that has no material you styling or concept

**Expected behavior**  
Just have a bottom sheet pop up with the title and then an icon and the name of the function next to it. 

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - Android: 13
 - Sync version: beta 19
 - Sync variant: internal

**Additional context**

**Comment by corylowry12** [comment]
This has since been added
