### ISSUE TITLE
Dropdown box text doesn't display on Inbox page when not using Expanded Toolbar

### ISSUE THREAD

**Issue by xaeraorg** [laurencedawson/sync-for-lemmy#161]
**Describe the bug**  
On the Inbox user page, with the Expanded Toolbar setting off, the text in the drop down doesn't display properly

**Steps to Reproduce**  
1. Go to Settings -> General
2. Turn off Expanded Toolbar
3. Go to the Inbox for the logged in account
4. The text for the dropdown box isn't displayed in Light or Dark mode

**Expected behavior**  
The text of the currently selected message/reply view in the dropdown should be visible.

**Screenshots**  
n/a

**Smartphone (please complete the following information):**
 - Device: S21 Ultra
 - Android: 13
 - Sync version: v23.07.31-11:10(20)
 - Sync variant: Beta

**Additional context**  
n/a

**Comment by laurencedawson** [comment]
Good spot. Fixed.
