### ISSUE TITLE
Sync doesn't share filters with web app block settings

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#162]
**Describe the bug**  
As a follow-up to #70, sync doesn't share filters with the web app

**Steps to Reproduce**  
1. Go to the website and block someone or a community
2. Then go to sync and press filters
3. Press appropriate section

**Expected behavior**  
Sync should be pulling from the API

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: [e.g. v22.5.20]
 - Sync variant: [e.g. pro]

**Additional context**

**Comment by laurencedawson** [comment]
Block and filters are two different things.

Filters are local where as blocking is already synced with the instance.

**Comment by pwd-github** [comment]
In that case, how do I access Blocks in Sync? It's also two things doing the same thing
