### ISSUE TITLE
App continually crashes after adding new account

### ISSUE THREAD

**Issue by brad-anderson** [laurencedawson/sync-for-lemmy#165]
**Describe the bug**  
After adding a new account, the app will crash once I switch to a different account or anonymous, then back to the new account. Once it crashes the first time it crashes within a second of opening Sync again (it displays the feed briefly).

Turning on airplane mode prevents the crash from occurring. The cached feed is displayed and I can click around but things like post comments won't load, of course. If I switch to Anonymous then back to the account it will crash even with Airplane mode on.

**Steps to Reproduce**  
1. Do a fresh install
2. Run first setup with defaults (also added Notification permission)
3. Hit Add Account
4. Enter login credentials (lemmy.world) using password manager (no 2FA)
5. Run through setup using defaults
6. Switch back to Anonymous
7. Switch back to newly added account
8. Crash

**Expected behavior**  
The best goddamn Lemmy app experience on the planet.

**Screenshots**  
N/A

**Smartphone (please complete the following information):**
 - Device: Samsung S21 Ultra
 - Android: 13
 - Sync version: v23.07.31-11:10
 - Sync variant: Internal (no Ultra sub yet).

**Additional context**  
Also happens if I use a lemm.ee account instead.

**Comment by laurencedawson** [comment]
Fixed
