### ISSUE TITLE
User highlights do not display in the inbox view

### ISSUE THREAD

**Issue by kringger** [laurencedawson/sync-for-lemmy#168]
**Describe the bug**  
Title

**Steps to Reproduce**  
1. Go to inbox and check reply from a user you have previously highlighted. 
2. Their name will not show as highlighted I'm the inbox view

**Expected behavior**  
Their name should be highlighted 

**Screenshots**  
None

**Smartphone (please complete the following information):**
 - Device: pixel 6 pro
 - Android: 13
 - Sync version: beta 21
 - Sync variant: beta 21

**Additional context**  
None

**Comment by laurencedawson** [comment]
Fixed.
