### ISSUE TITLE
Login Screen - Username  Field removes capital letters

### ISSUE THREAD

**Issue by MaroonBrian1928** [laurencedawson/sync-for-lemmy#17]
**Describe the bug**  
The username field when adding a new account removes capital letters when pasting or copying using a password manager.

**Steps to Reproduce**  
1. Add a new account
2. Copy text "FooBar"
3. Paste into user name field
4. Username appears as "ooar" because F and B have been removed.

**Expected behavior**  
Lemmy allows capital letters in usernames, so the username field should accept capital letters.

**Screenshots**  
![image](https://github.com/laurencedawson/sync-for-lemmy/assets/20406366/47798f63-e249-4abe-afee-2c092cdb2c78)
![image](https://github.com/laurencedawson/sync-for-lemmy/assets/20406366/a3e9767e-320a-431e-b6c7-ea635c7e78a4)

**Smartphone (please complete the following information):**
 - Device: Pixel; 6a
 - Android: 13
 - Sync version:  Internal Beta

**Comment by NomNuggetNom** [comment]
https://github.com/laurencedawson/sync-for-lemmy/issues/5

**Comment by MaroonBrian1928** [comment]
Closing duplicate, thank you @NomNuggetNom
