### ISSUE TITLE
Sharing a link to Sync using the Android share function produces a non-functional share page with "subreddit" reference

### ISSUE THREAD

**Issue by kringger** [laurencedawson/sync-for-lemmy#176]
**Describe the bug**  
Title

**Steps to Reproduce**  
1. Share a link to invoke the android share sheet
2. Click on 'Sync' and you will be presented with two options: 'Sync' and 'sync link handler'
3. Select 'Sync' (instead of 'sync link handler')
4. See the non-functional share page with "subreddit" reference

**Expected behavior**  
Explain the difference in functionality between 'sync' and 'sync link handler'. Send me to a functional page where I can enter a title and search for a Lemmy community to make a post. References to subreddits should be removed.

**Screenshots**  
![Screenshot_20230731-221444.png](https://github.com/laurencedawson/sync-for-lemmy/assets/35173157/cf036f58-6e0e-4b30-95ce-1566877dad0b)

**Smartphone (please complete the following information):**
 - Device: pixel 6 pro
 - Android: 13
 - Sync version: beta 23
 - Sync variant: beta 23

**Additional context**  
'sync link handler' is currently marked as TODO and it's functionality is not clear to the user. Issues either sync link handler' appear to be handled under a separate issue, but the differences between the two share options ('sync' and 'sync link handler') should be better explained.

**Comment by laurencedawson** [comment]
This hasn't been implemented yet:

https://github.com/laurencedawson/sync-for-lemmy/issues/37

You just found a workaround on the internal build lol
