### ISSUE TITLE
Navigation drawer still shows get sync ultra even though I have it

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#178]
Title

![Screenshot_20230801_064303_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/8837361/4722ec0a-9d02-4b91-a5ff-fac83ced9fa6)

**Comment by laurencedawson** [comment]
Looks like the webhook is working in discord!

**Comment by laurencedawson** [comment]
Unable to reproduce this.

**Comment by corylowry12** [comment]
It goes away after reopening the app. But if I go to the sync ultra settings and reset  my subscription and then restore it, it will show back up and will only go away after reopening the app.

**Comment by laurencedawson** [comment]
Aha

**Comment by laurencedawson** [comment]
Fixed for the next release.
