### ISSUE TITLE
Translate all does not display result

### ISSUE THREAD

**Issue by Ictinus** [laurencedawson/sync-for-lemmy#183]
**Describe the bug**  
Choosing to 'Translate all' only produces a dimmed post screen.

**Steps to Reproduce**  
1. Open a post that needs translating... https://lemmy.world/post/87537
2. Click on 'Comment options-->Translate all
4. See the post and comments dimmed but no translation result is shown.

**Expected behavior**  
I expect the post and comments to be translated to English.
Bonus points if I can choose a target language.

**Screenshots**  
![Screenshot_20230802-193346](https://github.com/laurencedawson/sync-for-lemmy/assets/2648495/eca03d88-15e9-43e8-a9ce-e09758a7a5e1)

**Device information**

    Sync version: v23.08.01-20:30    
    Sync flavor: googlePlay    
    
    View type: Slides    
    Push enabled: false    
    
    Device: oriole    
    Model: Google Pixel 6    
    Android: 13

**Additional context** 

Choosing an English language post/comments and requesting translation via the same method result in a toast message indicating translation complete.

Choosing a single foreign language comment action to Translate results in a similar dimmed screen, but the processing animation is displayed.

**Comment by Ictinus** [comment]
Some posts do succeed for translation.
Those that day they succeed but don't seem to have comments that are not loaded.

**Device information**

    Sync version: v23.08.02-18:53    Beta 25
    Sync flavor: googlePlay    
    
    View type: Smaller cards    
    Push enabled: false    
    
    Device: oriole    
    Model: Google Pixel 6    
    Android: 13

**Comment by laurencedawson** [comment]
There was actually a bug that didn't show the progress bar when you click translate all for the first time whilst the model is grabbed from Google.

I've fixed this and can confirm the text on the example given now loads.
