### ISSUE TITLE
Support login with email address

### ISSUE THREAD

**Issue by samuelspiza** [laurencedawson/sync-for-lemmy#186]
**Is your feature request related to a problem? Please describe.**  
Lemmy web UI supports logging in with email addresses as username. Sync currently prohibits entering '@' or '.' in the username field when setting up a new account.

**Describe the solution you'd like**  
Support email adresses as username for logging into lemmy instances.

**Comment by BettaSplendid** [comment]
This would be useful. I am going back to jerboa until it is possible to log in.

**Comment by samuelspiza** [comment]
Just so there is no confusion. I was able to login with my Lemmy username from the Instance. I just had my email set in my username field of my password manager. This works on the Web but not in Sync. When I manually entered my Lemmy username in Sync I was able to login.

**Comment by laurencedawson** [comment]
Fixed for the next release.
