### ISSUE TITLE
Viewing Inbox message in original context does not show comment being replied to

### ISSUE THREAD

**Issue by quadespresso** [laurencedawson/sync-for-lemmy#187]
**Describe the bug**  

Tapping Inbox message to view in original thread does not show the comment being replied to (my comment). It only displays the reply, with "View parent..." displayed above it.

**Steps to Reproduce** 

1. Go to Inbox
2. Tap on a message
3. Wait for Sync to take you to the original thread
4. Observe the same message that you saw in your Inbox
5. Note the lack of context, no view of your original comment

Workaround:

1. Tap "View parent..."
2. Wait for refresh/reload to complete
3. View original comment you wrote, along with the reply

**Expected behavior**  

1. From Inbox, tap message
2. Wait for Sync to nav to original thread
3. View the comment you had posted, along with the reply (that you were viewing in your inbox a moment ago)

**Screenshots**  

nil

**Smartphone (please complete the following information):**

 - Device: Samsung Galaxy S20 Note 5G
 - Android: 13
 - Sync version: v23.08.01-20:30 (24)
 - Sync variant: Ultra

**Additional context**  

N/A

**Comment by laurencedawson** [comment]
Fixed for the next release.
