### ISSUE TITLE
A dot between username and points in comments 

### ISSUE THREAD

**Issue by Madis0** [laurencedawson/sync-for-lemmy#188]
**Is your feature request related to a problem? Please describe.**  
I like seeing the domain next to usernames, but the distinction between the username domain and the points is too small.

**Describe the solution you'd like**  
An option to show a dot between the domain and comment points 

**Describe alternatives you've considered**  
A pipe (|) or more space maybe?

**Additional context**  
![IMG_20230802_171312](https://github.com/laurencedawson/sync-for-lemmy/assets/8611110/118e63b7-d2a4-4754-a408-c4a50f6c4b19)

**Comment by JamoDevNich** [comment]
I believe this does what you're after: [Settings shortcut: Comments > Delimit scores with a bullet point](sync-settings://26-delimit_preference)

![Screenshot_20230804-030623_1](https://github.com/laurencedawson/sync-for-lemmy/assets/9295293/97f51835-e2f1-4efc-ad5a-a65a3c91fb39)

![Screenshot_20230804-031119_1](https://github.com/laurencedawson/sync-for-lemmy/assets/9295293/b7c5893c-8a8f-4a69-a645-e070aa713975)
