### ISSUE TITLE
Add tag and Remove tag generate two toast messages each

### ISSUE THREAD

**Issue by Ictinus** [laurencedawson/sync-for-lemmy#189]
**Describe the bug**  
With an Ultra sub, Add tag and Remove tag generate two toast messages each.

**Steps to Reproduce**  
1. Go to 'Post options', choose 'Add Tag'
2. Provide tag and click 'Set'
3. See that two toast messages appear: first 'Tag added: <tag>', then 'Tag added'
4. Go to 'Post options', choose 'Remove tag'
5. See that two toast messages, 'Tag removed', appear one after the other.

**Expected behavior**  
For each action, only one toast message appears.

**Device information**

    Sync version: v23.08.01-20:30  Beta 24
    Sync flavor: googlePlay    
    
    View type: Smaller cards    
    Push enabled: false    
    
    Device: oriole    
    Model: Google Pixel 6    
    Android: 13

**Comment by laurencedawson** [comment]
Fixed for the next release.
