### ISSUE TITLE
Adding Instances (More than just the default instance)

### ISSUE THREAD

**Issue by SuperFes** [laurencedawson/sync-for-lemmy#190]
**Is your feature request related to a problem? Please describe.**  
I feel like it could be keen to add instances to browse anonymously, like the "default instance", except you could add any instance where you don't have an account.

**Describe the solution you'd like**  
Have an add instance option, that works just like the default instance.

**Describe alternatives you've considered**  
Obviously you could just go around creating accounts on all the Lemmy servers.

**Additional context**  
None, it's just an idea.

**Comment by brad-anderson** [comment]
I think this can be reworded to "Adding more than one Anonymous account". I was a little confused by what you meant.

**Comment by SuperFes** [comment]
Don't really feel like the request is unclear, it would be neat to be able to add instances in which you do not have an account for browsing their local, be nice to be able to see if their feed meets your expectations before you hop in.

Obviously this can be done via the web or whatever, or changing the one "Default Instance" you do have, it was just a thought that browsing without an account on other, or maybe in the same instance you do have an account on wouldn't be that bad of a feature.

**Comment by laurencedawson** [comment]
The latest update adds the ability to view other instances, view the local feed of that instance and favourite the instance.

I think that replaces the need for this.
