### ISSUE TITLE
Fold 4 not switching from inside display to cover display. 

### ISSUE THREAD

**Issue by PrawnStockton** [laurencedawson/sync-for-lemmy#191]
Closing my Z fold 4 with sync open locks the cover screen. When I unlock I'm on my home screen. Opening the device to the inside display with sync open behaves as expected and opens to tablet view. 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Z Fold 4 
 - Android: 13, one ui 5.1
 - Sync version: beta 24

**Comment by PrawnStockton** [comment]
Nevermind. For some reason sync was not selected in the "continue apps on cover screen" setting. I had previously set it to all apps so not sure what happened. Sorry!

**Comment by laurencedawson** [comment]
Glad its working now.
