### ISSUE TITLE
Add lemdro.id to the instance list

### ISSUE THREAD

**Issue by CorvetteCole** [laurencedawson/sync-for-lemmy#194]
**Is your feature request related to a problem? Please describe.**  
Hello, admin from lemdro.id here! We made it into the Play Store screenshots which was kinda cool, but sadly missing from the instance selection list.

**Describe the solution you'd like**  
Add lemdro.id to the instance selection list.

**Describe alternatives you've considered**  
Don't do that :(

Thanks!

**Comment by brad-anderson** [comment]
For anyone that doesn't realize it (you wouldn't be the first) you can type any instance hostname into that field. It isn't just limited to the dropdown options. lemdro.id should definitely be added though.

**Comment by laurencedawson** [comment]
Added for the next release <3
