### ISSUE TITLE
Very unhelpful bad login notification

### ISSUE THREAD

**Issue by Avenred** [laurencedawson/sync-for-lemmy#197]
**Is your feature request related to a problem? Please describe.**  
When logging in fails, you get a generic "Invalid login." toast. This seems to suggest that the username and password used are wrong, even when they're not. This also appears when attempting to login to an invalid (or down, in the case of lemmy.world) instance.

**Describe the solution you'd like**  
The little toast at the bottom is a little hard to notice. There's a bunch of blank space under the login button, so maybe errors could be put there instead?
Also, more helpful error messages would be nice. I should be able to tell the difference between the instance being down, or just entering in my details wrong.

**Describe alternatives you've considered**  
N/A

**Additional context**  
<img src=https://github.com/laurencedawson/sync-for-lemmy/assets/13921970/4515f2ee-87b3-49cf-b1ff-254f7b54fce2 alt="Login screen for Sync with invalid login toast at the bottom" height="500">

**Comment by ubergeek77** [comment]
I considered making an issue for this, but I cannot sign in at all. I've heard similar reports from others.

If this issue doesn't gain any traction, I'll make one to specifically track login issues.

**Comment by laurencedawson** [comment]
Unfortunately whats returned by lemmy isn't much better.
