### ISSUE TITLE
'Legitimate Interest' GDPR consent settings does not save

### ISSUE THREAD

**Issue by Murvel** [laurencedawson/sync-for-lemmy#200]
When deselecting consent for 'Legitimate Interest' it does not save and it seems you cannot opt-out. 

**Expected behavior**  
The opt-out option should be the same state as when you've confirmed your choices.

**Smartphone (please complete the following information):**
 - Device: Samsung S20?
 - Android: 13
 - Sync version: v23.08.01-20:30
 - Sync variant: Standard

**Comment by laurencedawson** [comment]
As discussed here:

https://lemmy.world/comment/2054070

Clicking on revoke does just that. It removes your previous setting and you start the process again.

With Admob there is no way to review your previous selection.
