### ISSUE TITLE
Images in Comments

### ISSUE THREAD

**Issue by ThePillarist** [laurencedawson/sync-for-lemmy#203]
**Is your feature request related to a problem? Please describe.**  
The image format when adding to a comment offers to upload but not to post from a link. 

**Describe the solution you'd like**  
Since Lemmy suggested using that format to keep loads of servers could that be added? 

**Describe alternatives you've considered**  
N/A adding a section to post a link to the image in addition the upload option should be simple enough

**Additional context**  
Add any other context, screenshot(s) or video(s) about the feature request here.

**Comment by laurencedawson** [comment]
Not sure what you mean here. You can already upload on the submit and comment pages.

**Comment by ThePillarist** [comment]
I believe the request I had in mind was when you click on to add an image, where it says Sources and offers Camera or Galley could there be a space to put a link to an image, since when lemmy.world was having issues one of their posts said to avoid uploading images for comments and posts and just use the link to an image.

**Comment by laurencedawson** [comment]
Added support for inserting from a link when the image button is clicked.
