### ISSUE TITLE
Crash when using lemmy.ca instance

### ISSUE THREAD

**Issue by owenlejeune** [laurencedawson/sync-for-lemmy#204]
**Crash when using any view/theme customizations**  
When using *lemmy.ca* as my instance, the app will crash every time it's opened

**Steps to Reproduce**  
1. Log-in to a lemmy.ca account or set the home instance to lemmy.ca
2. Force quit the app
3. Re-open the app
4. See crash

**Expected behavior**  
App should open and work as expected.

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - Android: 13
 - Sync version: v23.08.01-20:30
 - Sync variant: Lemmy

**Additional context**  
Seems to only be occurring on my home instance *lemmy.ca*

**Comment by kratoz29** [comment]
I have the same issue but with lemmy.world, I discovered this could not be instance related but something about the communities/subscribed list.

My main account is from Lemmy.world, but then I created two additional accounts to lemmy.fmhy.net and lemm.ee no crashes whatsoever, until I used the tool called LASIM https://github.com/CMahaff/lasim to migrate my communities from Lemmy.world to lemm.ee, I got an instant crash with no other way to fix it but cleaning all app data or reinstalling it.

LASIM reports the subscribed communities from Lemmy.world are 537, so it is a big number I guess, something to have in mind.

If I use my fresh new account from lemmy.fmhy.net it won't crash.

**Comment by owenlejeune** [comment]
Interesting, yeah the crash doesn't seem to occur when the home instance is lemmy.ca but I'm not signed in. But it does crash when I am in. I do have a fairly extensive subscription list from a number of instances so I suspect you're onto something with your subscriptions theory.

**Comment by laurencedawson** [comment]
I think this has since been fixed.
