### ISSUE TITLE
disable downvote on relevant instances

### ISSUE THREAD

**Issue by Phuntis** [laurencedawson/sync-for-lemmy#206]
certain instances like beehaw.org disable the downvote button in the web ui and disable downvotes so you can't downvote even if you have a button but sync still shows the button even on those instances

**Comment by NiaTheCat** [comment]
Would just like to add this in case it helps out any if this gets developed, the relevant API to check if an instance has downvotes enabled is here:
https://join-lemmy.org/api/interfaces/LocalSite.html#enable_downvotes

**Comment by laurencedawson** [comment]
Added for the next release.
