### ISSUE TITLE
Support for viewing instance page

### ISSUE THREAD

**Issue by donnielrt** [laurencedawson/sync-for-lemmy#207]
**Is your feature request related to a problem? Please describe.**  
It's helpful to be able to view information about an instance like it's about page, etc. as well as having the ability to block it from that page. ~~Adding a block from an instance from settings is nice, but it's many taps away~~ (just realized you can block an instance from a post using the "filter" submenu!).

**Describe the solution you'd like**  
There should be a way to view an instance page from a post like we can view a community. This page should include the instance information and a block button.

**Describe alternatives you've considered**  
Maybe there could be an instance sidebar on a post.

**Additional context**  
Add any other context, screenshot(s) or video(s) about the feature request here.

**Comment by laurencedawson** [comment]
This has since been added.
