### ISSUE TITLE
"More actions" button crashes app in comments

### ISSUE THREAD

**Issue by jordan1776** [laurencedawson/sync-for-lemmy#210]
**Describe the bug**  
App crashes when pressing "more actions" button when in comment view.

**Steps to Reproduce**  
1. Press any post to go the comments
2. Press the 3 dot menu at the top to open the "more actions" pane
3. Crash

**Expected behavior**  
That button should open the "more actions" pane without crashing the app.

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: Xperia 1 Ii
 - Android: 11
 - Sync version: 23.08.02-22:21
 - Sync variant: Ultra

**Additional context**

**Comment by Cerothen** [comment]
I can verify this is also happening to me.

Android 13
Samsung S21

**Comment by JoseALermaIII** [comment]
I've been able to consistently reproduce this issue since launch.
Video too large to attach, so uploaded here:
https://drive.google.com/file/d/1N_9fxnClpgGuHMnQd4ZJK7l0T1ycqjPR/view?usp=drivesdk

**Device information**

    Sync version: v23.08.23-18:29    
    Sync flavor: googlePlay    
    
    Ultra user: false    
    View type: Slides    
    Push enabled: false    
    
    Device: bonito    
    Model: Google Pixel 3a XL    
    Android: 12

Please let me know if I can provide additional information.

**Comment by jojosteez** [comment]
Wanted to add that I have also been experiencing this since launch.
Samsung Galaxy Fold 4
Android 13

I have Ultra, if that makes any difference.

**Comment by jordan1776** [comment]
This issue is reproducible on my new phone on beta 34
Sony Xperia 1 V, Android 13
I also have Ultra, I wonder if this issue is related to importing settings from the Reddit app

**Comment by JoseALermaIII** [comment]
> This issue is reproducible on my new phone on beta 34
> Sony Xperia 1 V, Android 13
> I also have Ultra, I wonder if this issue is related to importing settings from the Reddit app

Yep, I think importing settings is it. When I switch to the Anonymous profile, it works as expected.

**Comment by jojosteez** [comment]
> > This issue is reproducible on my new phone on beta 34
> > Sony Xperia 1 V, Android 13
> > I also have Ultra, I wonder if this issue is related to importing settings from the Reddit app
> 
> Yep, I think importing settings is it. When I switch to the Anonymous profile, it works as expected.

It definitely is.  I reproduced this on both a phone and tablet.  So I deleted my profile and logged in again without importing settings and the menu works as intended.  I also brought up the issue in the Discord to gauge if more users are affected.

**Comment by laurencedawson** [comment]
The update I just submitted should fix this issue.
