### ISSUE TITLE
Server Donations

### ISSUE THREAD

**Issue by BramWarrick** [laurencedawson/sync-for-lemmy#212]
Lemmy has a solid contingent of people marveling and aghast at the cost. That people can have the money for Sync at any level baffles some.

We're also mobbing an already full server.

I'd like a seamless way to donate to the server(s) where Sync takes $0. It can be a direct link to their server site or something else. If we have cash for Sync, maybe we should have cash for the servers of the fediverse.

We can't buy goodwill, but we can soften the downsides of swelling membership. We need to be good partners.

**Comment by joeyalexander** [comment]
I think direct donations to the server are a good idea, but I'm not sure it should be on Sync for Lemmy to do much of the heavy lifting.

At the moment, the Lemmy devs 'official' stance is to simply put a donation link the instance sidebar which users can follow: [https://github.com/LemmyNet/lemmy/issues/2332#issuecomment-1166723252](https://github.com/LemmyNet/lemmy/issues/2332#issuecomment-1166723252)

But this means every instance has a different way of linking to different fundraising websites. Just to name a few for example:

- lemmy.world has a couple of links to opencollective.com and patreon.com
- discuss.tchncs.de has a link to tchncs.de/donate
- sh.itjust.works does not have any donation links in the sidebar

That's not to mention that every instance (by default) has a link to join-lemmy.org/donate at the top to donate to the Lemmy devs as well.

I think it's unreasonable to expect Sync for Lemmy to account for every possible variation of a donation link (if it exists) in the sidebar.
The easiest solution would be to allow the user to read the sidebar themselves, which has been suggested in ticket #39 or perhaps get the Lemmy devs to implement a proper donation link which can be accessed via the API.

**Comment by brad-anderson** [comment]
I think logistically it would be hard for a solo developer (as Sync has) to manage some sort of instance payment network but maybe some day.

I love the idea of anything that will help us keep Lemmy user funded and anything Sync can do to encourage donations to instances would be a great addition.

**Comment by laurencedawson** [comment]
I think making it more prominent in app would be good however taking payments in-app would result in 15-30% being taken by Google at source.

**Comment by laurencedawson** [comment]
https://github.com/LemmyNet/lemmy/issues/3793

Closing as this should be handled by the main lemmy project.
