### ISSUE TITLE
Sync does not render embedded gifs

### ISSUE THREAD

**Issue by d3-X-t3r** [laurencedawson/sync-for-lemmy#213]
**Describe the bug**  
In a post with mixed pngs and static gifs embedded using the `![]()` syntax, Sync only displays the pngs and not the gifs. 

**Steps to Reproduce**  
1. Create a new comment with a gif enclosed in `![]()`

**Expected behavior**  
Gif should be rendered 

**Screenshots**  
![Screenshot_20230803_200715_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/1624052/f4c26c59-490b-4c08-afe4-7f8161fdecb5)

The left pane shows Sync, the right pane is the same comment rendered in Firefox. The missing images are .gifs, whereas the ones which rendered are .pngs.
Here's a link to the comment: https://lemmy.world/comment/2005403

**Smartphone (please complete the following information):**
 - Device: Galaxy Fold 4
 - Android: 13
 - Sync version: v23.08.02-22:21 
 - Sync variant: Ultra / googlePlay 

**Additional context**

**Comment by laurencedawson** [comment]
Tested and I can no longer repeat this issue:

https://lemmy.world/comment/8349695

Closing unless you come across another.
