### ISSUE TITLE
Tap to Collapse Comments 

### ISSUE THREAD

**Issue by Xusontha** [laurencedawson/sync-for-lemmy#215]
Similar to how Liftoff's comments work, it would be nice if there was a feature which would make it so instead of tapping to show comment options and long pressing to collapse the comment thread, to make the comment options show up on a long press and the comment thread to collapse on a tap

**Comment by academician** [comment]
This exists, but is a bit hard to find:

Settings -> Comment options -> Single click to hide comment

To mimic Liftoff's behavior you can also turn on "Collapse parent" just below it.

**Comment by Xusontha** [comment]
Of course I looked at every setting but somehow managed to miss that one...
