### ISSUE TITLE
Unable to direct share image

### ISSUE THREAD

**Issue by TheEvilDrCube** [laurencedawson/sync-for-lemmy#216]
**Describe the bug**  
When clicking on Direct in the Share menu, nothing happens.

**Steps to Reproduce**  
1. Go to image
2. Click more on FAB
3. Click on Share
4. Click on Direct
5. See error

**Expected behavior**  
When clicking on Direct, the Android share menu should appear showing contacts and apps to share through. 

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - Android: 14.1 Beta
 - Sync version: Beta v. 26
 - Sync variant: Free

**Additional context**  
I'm not sure if this is a known issue or simply not properly implemented as of now. Couldn't find another bug report or see anywhere if it wasn't implemented yet.

**Comment by sum1su** [comment]
Same device, Same Android Version and same Bug.

**Comment by laurencedawson** [comment]
Can't replicate. Could be an Android 14 issue, I'll keep an eye on this.

**Comment by DavisJ3608** [comment]
I'm having the same problem - Galaxy S23 Ultra on the OneUI 6.0/Android 14 beta. The Samsung changelog said something about "displaying a preview of an image in the share menu" so you can, I guess, get one more shot at not accidentally sending grown-up selfies with Grandma or whatever.

**Comment by laurencedawson** [comment]
Fixed for the next release.
