### ISSUE TITLE
Having sort by controversial 

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-lemmy#219]
**Is your feature request related to a problem? Please describe.**  
No controversial sort 

**Describe the solution you'd like**  
Having a sort by controversial as it seems to have been handled recently by lemmy

https://discord.com/channels/684912692485554230/1120741766820286464/1136686805966667806

**Comment by brad-anderson** [comment]
Controversial was actually reverted just prior to release, so it's not in just yet.

See: https://github.com/LemmyNet/lemmy/commit/6bc86baddc6eb0d73722a8f722420951d7cd72f1

**Comment by laurencedawson** [comment]
This has since been added.
