### ISSUE TITLE
filters don't work

### ISSUE THREAD

**Issue by Phuntis** [laurencedawson/sync-for-lemmy#22]
I added a community to the community filters list and I can still see it in the everything feed

whoops delete this sorry I searched filter on here to avoid dupes but then someone had the same issue and filled it out at the same time so duplicate sorry

**Comment by NomNuggetNom** [comment]
Duplicate of https://github.com/laurencedawson/sync-for-lemmy/issues/21

**Comment by laurencedawson** [comment]
Closing duplicate.
