### ISSUE TITLE
Crash after signing in and opening the app a second time

### ISSUE THREAD

**Issue by wason-sonico** [laurencedawson/sync-for-lemmy#224]
**Describe the bug**  
Using the app without an account works just fine but once you login, use the app and close it, when you open the app again it'll crash every time.

**Steps to Reproduce**  
1. Log in
2. Use the app as usual
3. Close the app
4. Open it again. It'll crash

**Expected behavior**  
The app should open normally.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi K40 Gaming
 - Android: 13
 - Sync version: v23.08.02-22:21

**Comment by wason-sonico** [comment]
Hi. Someone mentioned here that having too many subscriptions is causing crashes. Might be the reason.
https://sh.itjust.works/comment/1772420

**Comment by ampz9** [comment]
I was seeing this yesterday, but no longer after today's update

**Comment by wason-sonico** [comment]
Yes. New version v23.08.03-16:15 seems to have fixed this. Thanks!
