### ISSUE TITLE
[Feature Request] Block Community option added to Post Menu

### ISSUE THREAD

**Issue by CharlieDestroyerOfTacos** [laurencedawson/sync-for-lemmy#225]
**Is your feature request related to a problem? Please describe.**  
A "Block Community" option in the 3dot menu of each post would be incredibly helpful, as it would allow the user to block any community while scrolling the Everything feed without having to actually visit the community. 

**Describe the solution you'd like**  
A basic "Block Community" option in the 3dot menu of each post. 

**Describe alternatives you've considered**  
A "Block Community" option added to the More Actions menu.

**Comment by pwd-github** [comment]
isn't this already under filters?

**Comment by josephmgaffney** [comment]
> isn't this already under filters? 

Yes, which is why it should be a contextual menu at the post.

**Comment by laurencedawson** [comment]
Added.
