### ISSUE TITLE
Change Upvote and Downvotes arrow colours to match Lemmy's colours

### ISSUE THREAD

**Issue by MetalZealot** [laurencedawson/sync-for-lemmy#226]
**Is your feature request related to a problem? Please describe.**  
The current orange and blue arrows are a  remnant from this app's predecessor, and doesn't match the existing aesthetic of Lemmy's interface

**Describe the solution you'd like**  
Change the colours to match the respective arrows of the default colour scheme.

**Describe alternatives you've considered**  
A possible alternative, if the arrow colours are too heavily associated with the logos colours and would possibly be seen as off-brand, maybe implement colour options for the arrows in the Theming settings page?

**Comment by laurencedawson** [comment]
Added support for this in the previous release.
