### ISSUE TITLE
View More button appears in the wrong place and behaves wrongly

### ISSUE THREAD

**Issue by AlexVasiluta** [laurencedawson/sync-for-lemmy#233]
**Describe the bug**  
The `view more` button appears at the top of the reply chain and, when clicked, says that no comments were added.

**Steps to Reproduce**  
1. Go to https://feddit.de/post/2136244
2. Scroll down to comments
3. See incorrect View More

**Expected behavior**  

**Screenshots**  
![Screenshot_20230804_092417_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/16223925/8c29f892-a05f-4570-92d9-8bf3a14e6b20)

**Smartphone (please complete the following information):**
**Device information**

    Sync version: v23.08.03-16:15    
    Sync flavor: googlePlay    
    
    Ultra user: true    
    View type: Slides    
    Push enabled: false    
    
    Device: r9q    
    Model: samsung SM-G990B    
    Android: 13

**Additional context**  
lemmy.ml is running on 0.18.3 and my home instance is running 0.18.2. That may have something to do with it? I don't think it does, however, since my alt account on lemmy.world is behaving similarly.

**Comment by laurencedawson** [comment]
Fixed for the next release.
