### ISSUE TITLE
Error toast when no posts available says "sub has no posts" instead of community

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-lemmy#234]
![tempFileForShare_20230804-103239.jpg](https://github.com/laurencedawson/sync-for-lemmy/assets/55349349/a30101ab-935c-4e22-8192-3c34082f8291)

https://discord.com/channels/684912692485554230/685907856351821824/1136909685497270272

**Comment by laurencedawson** [comment]
Nice, fixed.
