### ISSUE TITLE
Wrong permalink instance

### ISSUE THREAD

**Issue by AlexVasiluta** [laurencedawson/sync-for-lemmy#235]
**Describe the bug**  
During the filing of #233, i have stumbled upon another strange behavior, however I don't fully know if it's fixable. My account's home instance is lemmy.world, the posts's instance is lemmy.ml, however when I go to !asklemmy@lemmy.ml and 3 dots -> copy -> copy permalink, it gives me the link from another instance. 

For example, [this](https://feddit.de/post/2136244), [this](https://sh.itjust.works/post/2168204) and [this](https://feddit.nl/post/1225388) are all 3 different referenced instances that are not on the posts' original instances, but i got permalinks from the copy button. It seems like it happens a lot of the time when accessing posts not from the home instance, and that makes sense.

**Steps to Reproduce**  
1. Go to any post mentioned above, in the app
2. See that it isn't on the main instance of the post
3. Copy permalink
4. Still not from instance

**Expected behavior**  
I get a permalink to the posts's instance, not a different one.

**Screenshots**  

**Smartphone (please complete the following information):**
 **Device information**

    Sync version: v23.08.03-16:15    
    Sync flavor: googlePlay    
    
    Ultra user: true    
    View type: Slides    
    Push enabled: false    
    
    Device: r9q    
    Model: samsung SM-G990B    
    Android: 13

**Additional context**  
N/A

**Comment by AlexVasiluta** [comment]
Just after I finished filing the bug report, i realized that those weird instances are the home instances of the OPs', not the post's! It makes sense if you squint at it, but I still don't think it's intuitive/correct to be this way..

**Comment by pwd-github** [comment]
> Just after I finished filing the bug report, i realized that those weird instances are the home instances of the OPs', not the post's! It makes sense if you squint at it, but I still don't think it's intuitive/correct to be this way..

That's just the way that Lemmy is designed. Maybe start a discussion about it at !lemmy_support@lemmy.ml

**Comment by laurencedawson** [comment]
The permalink is correct I'm afraid.
