### ISSUE TITLE
Title markdown not supported

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-lemmy#236]
**Describe the bug**  
On lemmy, markdown is also supported in the title of the post, but Sync doesn't really know how to handle that. Also (but this has also been a S4R issue for a while), the preview body's markdown isn't rendered and displays all the unformatted text to the user

**Expected behavior**  
Title should render properly

https://discord.com/channels/684912692485554230/685907856351821824/1136919104498966528

**Comment by laurencedawson** [comment]
Huh TIL. Thanks for the report

**Comment by laurencedawson** [comment]
Added support for markdown in titles.
