### ISSUE TITLE
Tapping into a post, Sync stops displaying the instance of users 

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#237]
**Describe the bug**  
Tapping into a post, Sync stops displaying the instance of users. 

**Steps to Reproduce**  
1. Go to your feed
2. Click on a post 
3. Look at all users in the post

**Expected behavior**  
Sync should display the instance of all users

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: Version v23.08.03-16:15
 - Sync variant: [e.g. pro]

**Additional context**

**Comment by laurencedawson** [comment]
Not quite following here. Is this not due to the users belonging to that instance?

**Comment by pwd-github** [comment]
Nope, it's not showing the instance for everyone

**Comment by pwd-github** [comment]
Nope, look here. 

![Screenshot_20230827-123418](https://github.com/laurencedawson/sync-for-lemmy/assets/203217/378964df-481a-4ec9-903e-504d2219d39e)

![Screenshot_20230827-123424](https://github.com/laurencedawson/sync-for-lemmy/assets/203217/dab460d5-85fe-4053-b682-e92724a454bd)

![Screenshot_20230827-123430](https://github.com/laurencedawson/sync-for-lemmy/assets/203217/4e3dc3c8-1afa-4e8a-b952-da68de51f06b)

**Comment by laurencedawson** [comment]
Added.
