### ISSUE TITLE
Expose instance name and view its communities

### ISSUE THREAD

**Issue by oh1apps** [laurencedawson/sync-for-lemmy#242]
Instance name from which post origins could be visible in post header. 

Also viewing instance communities would be nice. These two can be combined - so clicking on instance name brings list of its communities

**Comment by waldyrious** [comment]
There was a [thread in !syncforlemmy@lemmy.world](https://lemm.ee/post/2912551) asking for this, with a bunch of supporting comments and upvotes. The title (in case it helps with search) is "[Feature suggestion] Option to list all the communities of an instance".

**Comment by laurencedawson** [comment]
Added for the next release.
