### ISSUE TITLE
Random NSFW

### ISSUE THREAD

**Issue by zebs1** [laurencedawson/sync-for-lemmy#246]
Sync for Reddit had a "random NSFW" feature 

**Describe the solution you'd like**  
Sync for Lemmy to have the same/similar feature 

**Describe alternatives you've considered**  
Absention.

**Additional context**  
Add any other context, screenshot(s) or video(s) about the feature request here.

**Comment by DavisJ3608** [comment]
To be fair, this feature was built into Reddit - Sync just used that service and presented the results in the app. If someone on Lemmy developed a similar feature, or even just curated a list, it might be possible to integrate.

**Comment by laurencedawson** [comment]
Added for the next release.
