### ISSUE TITLE
Restoring Purchase on Chromebook Gives Error

### ISSUE THREAD

**Issue by TigerCraneStyle** [laurencedawson/sync-for-lemmy#248]
**Describe the bug**  
When going through the setup after installing Sync on my Chromebook, it asks if I want to restore purchases. When selecting "Restore", a toast message pops up that says "No purchases found (20)". The problem is that I purchased the yearly subscription on my Pixel Fold a couple of days ago. The same error happens if you go through the initial setup and then go to settings to restore purchases.

**Steps to Reproduce**  
1. Install app.
2. Tap "Next" on the Sync welcome screen.
3. Tap "Accept" on the Terms and Conditions screen.
4. Tap "Restore" on Restore Purchases screen.
5. "No purchases found (20)" toast message will pop up on the bottom of the screen.

Alternative method...

1. Go through the initial setup after installing the app.
2. Tap the gear icon on the left side of the screen to go into Settings.
3. Scroll down to "Restore Purchases" and tap it.
4. Tap on "Restore".
5. "No purchases found (20)" toast message will pop up on the bottom of the screen.

**Expected behavior**  
After tapping the "Restore" button on either of the above methods, my yearly subscription should have been restored.

**Screenshots**  
Screenshot added that shows error toast message on the bottom.

**Smartphone (please complete the following information):**
 - Device: Lenovo Flex 5 Chromebook
 - Android: Google ChromeOS Version 114.0.5735.239 (Official Build) (64-bit)
 - Sync version: Sync for Lemmy Beta 27
 - Subscription was purchased on a Pixel Fold
 

![PXL_20230804_200854082~2](https://github.com/laurencedawson/sync-for-lemmy/assets/131628729/20f04557-1bff-4569-bcae-d1fdd936bef1)

**Comment by danielnguyen** [comment]
Getting the same issue but on a Lenovo Tab M8 (Android 11, Sync beta 27). Previously purchased Sync Ultra on a Pixel 7 pro.

![Screenshot_2023-08-06-00-27-51-791](https://github.com/laurencedawson/sync-for-lemmy/assets/845913/86ea06ad-ee08-4542-b62a-74bfd046aa97)
![Screenshot_2023-08-06-00-24-36-095](https://github.com/laurencedawson/sync-for-lemmy/assets/845913/940195af-e3ea-4147-a41f-06d4091817f6)

**Comment by corylowry12** [comment]
Can you try going to the sync ultra page and scrolling down and hitting restore?

**Comment by TigerCraneStyle** [comment]
> Can you try going to the sync ultra page and scrolling down and hitting restore?

Out of the three options to restore purchase, that's the only one that works! Thanks, Cory.

**Comment by corylowry12** [comment]
> > Can you try going to the sync ultra page and scrolling down and hitting restore?
> 
> Out of the three options to restore purchase, that's the only one that works! Thanks, Cory.

No problem!
