### ISSUE TITLE
Explore in 'More Actions' fails to open a fragment.

### ISSUE THREAD

**Issue by GittyMac** [laurencedawson/sync-for-lemmy#25]
**Describe the bug**  
When Explore is clicked from the 'More Actions' menu, a toast appears showing that a fragment failed to load.

**Steps to Reproduce**  
1. Go to 'More Actions'
2. Click on 'Explore'
3. See error

**Expected behavior**  
The Explore menu should appear.

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - Android: 14 Beta 4
 - Sync version: v23.07.24-19:51
 - Sync variant: Internal

**Additional context**  
The toast cuts off, not showing the full error.

**Comment by laurencedawson** [comment]
Fixed.
