### ISSUE TITLE
Summarize article/post/comment feature for Ultra

### ISSUE THREAD

**Issue by brad-anderson** [laurencedawson/sync-for-lemmy#251]
**Is your feature request related to a problem? Please describe.**  
Long winded articles and comments.

**Describe the solution you'd like**  
I recently started using the Summarize feature that [Kagi](https://kagi.com/) started providing for its users, and it's pretty handy for when an article is longwinded. They offer a [paid API](https://kagi.com/summarizer/api.html). There are other companies that offer similar services. [TLDRThis](https://rapidapi.com/tldrthishq-tldrthishq-default/api/tldrthis). [OneAI](https://www.oneai.com/summarize).  Whatever the AutoTLDR bot uses (I can't see the FAQ because the subreddit is private in protest). Probably some self hosted stuff you could use. I can't speak to the relevant quality of them.

**Describe alternatives you've considered**  
Not being lazy, but I've dismissed this as unworkable.

There is, of course, the autotldr bot that can be found on both reddit and Lemmy which sort of already does this for articles but I don't see it show up that often.

**Comment by laurencedawson** [comment]
Nice idea

**Comment by laurencedawson** [comment]
Added for the next release!
