### ISSUE TITLE
Add Translate Text option in addition to Extract Text Ultra Feature

### ISSUE THREAD

**Issue by brad-anderson** [laurencedawson/sync-for-lemmy#252]
**Describe the solution you'd like**  
Because I use the Everything/All feed a lot more with Lemmy to find new content I end up seeing a lot of memes and image content in other languages. It'd be great if you could translate the text of these. I found [a guide on Google Cloud's docs](https://cloud.google.com/translate/docs/hybrid-glossaries-tutorial) to do this so it seems like it'd be pretty straight forward.

Even better would be to replace the original text in the image with the translated text like Google Translate can do with your camera but I don't see this being offered in the Google Cloud Translate features.

**Describe alternatives you've considered**  
I've copied and pasted the extracted text into Google Translate manually, but it's awkward to do that and hard to understand what is being written without being able to look at the source image.

**Comment by laurencedawson** [comment]
Great idea.

Added for the next release.
