### ISSUE TITLE
"lemmy.world is having issues" prompt while feed loads perfectly fine behind it.

### ISSUE THREAD

**Issue by Vlixz** [laurencedawson/sync-for-lemmy#26]
**Describe the bug**  
When completely closing the app and reopening it, the "lemmy.world is having issues" prompt is shown although everything loads perfectly fine behind it.

**Steps to Reproduce**  
1. Login with lemmy.world account.
2. Completely close the app.
3. Open the app.
4. The prompt is shown.

**Expected behavior**  
No prompt is displayed.

**Screenshots**  
![Screenshot_20230724-234211.jpg](https://github.com/laurencedawson/sync-for-lemmy/assets/71019504/ae4cc08c-bef4-448c-809e-0e218a0f6504)

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord
 - Android: Andriod 11
 - Sync version: v23.07.14
 - Sync variant: Lemmy

**Comment by NomNuggetNom** [comment]
I think it's based on this: https://lemmy-world.statuspage.io/. As of writing it says there are "elevated response times"

**Comment by Vlixz** [comment]
That could definitely be the case! Wasn't completely sure how sync figured out when a server was down or having issues (maybe something went wrong there). But if sync uses a external source for it, then this can probably be closed.

**Comment by laurencedawson** [comment]
Sadly its down to the status page to report this.
