### ISSUE TITLE
Pressing community icon from feed doesn't work

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#27]
**Describe the bug**  
If you're in Everything/Subscribed, pressing a profile picture on a thread should take you to the profile

**Steps to Reproduce**  
1. Open subscribed
2. Press a profile picture
3. Wallow in dissapointment
4. Make sad eyes

**Expected behavior**  
It should open the user profile

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - Android: 13
 - Sync version: internal beta 
 - Sync variant: N/A

**Additional context**

**Comment by laurencedawson** [comment]
Could you take a screenshot to show what you mean here please? Thanks

**Comment by pwd-github** [comment]
> Could you take a screenshot to show what you mean here please? Thanks

My bad, poor terminology from me, it's the community icon

**Comment by pwd-github** [comment]
![Screenshot_20230725-160756](https://github.com/laurencedawson/sync-for-lemmy/assets/203217/624a56fb-88a1-42f4-9fb6-4e5fbba12bf4)

**Comment by laurencedawson** [comment]
Fixed, cheers!
