### ISSUE TITLE
Displaying more server side info for home instance

### ISSUE THREAD

**Issue by ruffsl** [laurencedawson/sync-for-lemmy#273]
**Is your feature request related to a problem? Please describe.**  
When attempting to connect to a home instance, it could be helpful for users to show diagnostics info alongside the selected instance, e.g. such as backend version number. Given many issues and features are tied to specific releases of Lemmy, displaying that could help disambiguate if a regression is due to a client side or server side change.

**Describe the solution you'd like**  
Could just show this info in the Lemmy instance settings menu dialogue.

**Describe alternatives you've considered**  
I suppose users could also open a browser to load the web UI to check the back end version, but I suppose there might be more contextual info the API provides that the web UI might not surface already.

**Additional context**  
This might also be a nice place to include reported status telemetry for the instance in question by aggregating from third-party reporters:
- https://lemmy-status.org/
- https://lestat.org/

**Comment by laurencedawson** [comment]
Closing dupe.
