### ISSUE TITLE
Add option to copy body text from post

### ISSUE THREAD

**Issue by ruffsl** [laurencedawson/sync-for-lemmy#281]
**Is your feature request related to a problem? Please describe.**  
The current copy options for a OP post include [`Copy title`, `Copy permalink`, `Copy link`, `Copy username`]. A notable option missing from this would be `Copy text`. This would allow users to copy text from the body of a post, making it easier to share exact quotes, to read aloud via Text-to-speech engines, or pass along to other third-party accessibility apps that leverage Android's clipboard.

![Screenshot_20230810_185517_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/2293573/aa776ce2-4cd5-48af-94c1-9ced69d8ff84)

**Describe the solution you'd like**  
Simply add `Copy text` as a option within the `Copy` popup menu.

I'd also recommend copying the design language used in the `Share` menu option, where vertical ellipsis `⋮` are used as modifier options to a common button action, specifically using `Copy text` as the default action for the top level `Copy` button in the `Post options` and `Comment options` popup menus. This would cut down my most used feature in sync from a sequence of 4 UI gestures down to 3.

**Describe alternatives you've considered**  
Perhaps there could be an option to more seamlessly support in-app text highlighting, allowing the user to use Android's native text selection UI. E.g. long-long press action on post-text or comment-text (when vertical scrolling or swiping touch gestures not detected) to create a cursor within the text field, enabling the user to sub-highlight or select-all as per usual for any text, as done from any browser.

Or, perhaps long-long-press and hold gestures could be user mappable. So that `Copy text` could be achievable via a single UI gesture event.

**Additional context**  
In Lemmy's web UI (as with most markdown based forums, such as Discourse and GitHub), users can view the source text (or raw markdown) as well to better inspect or copy exact formatting of either body text in posts or text in comments. Given that most screen readers handle reading rich text a lot better than reading raw markdown, it would be nice if the default copy text to clipboard feature used the rendered markdown as reference, rather than the raw markdown text itself. But perhaps it would be more than worth it to also allow the user to still view and copy from the raw markdown source when explicitly requested.

**Comment by laurencedawson** [comment]
Good spot. Fixed for the next release.
