### ISSUE TITLE
Enhancement: Load parent when clicking on comment reply in inbox

### ISSUE THREAD

**Issue by Coffee-Viking** [laurencedawson/sync-for-lemmy#285]
**Is your feature request related to a problem? Please describe.**  
When receiving comment replies in the inbox, especially if it's after a couple hours, I might not remember the exact context anymore and click on the respective message to go to the original conversation.

Here however Sync only loads the comment I've clicked on, and I have to click "view parent" to see my own original comment to remember the context.

**Describe the solution you'd like**  
Automatically load the parent comment (= my own) together with the comment reply on clicking the respective comment, to seamlessly show the message exchange history.

Alternatively (probably more complex?) create a user setting "ghost quote" that shows my initial comment plus the reply already in my inbox so I can reply from there directly, even if the comment I received didn't quote my original message.

**Describe alternatives you've considered**  
Click that damn "show parent" button each and every time 🙄

**Additional context**  
Video of current state https://imgur.com/a/2qOniQO

**Comment by laurencedawson** [comment]
I've switched to loading the entire context here.
