### ISSUE TITLE
Recents thread list links to reddit url 

### ISSUE THREAD

**Issue by knightry** [laurencedawson/sync-for-lemmy#289]
**Describe the bug**  
When clicking a post in the list of recently viewed threads, aka Recents, it opens a reddit url instead of the appropriate lemmy url. 

**Steps to Reproduce**  
1. Go to Recents
2. Click on any thread
3. See reddit app or reddit url. 

**Expected behavior**  
Expect it to open the thread in Sync for Lemmy. 

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - Android: 13
 - Sync version: version v23.08.03-16:15

**Comment by Coffee-Viking** [comment]
Confirmed. Up until now I have never even heard of that feature.

**Comment by laurencedawson** [comment]
Good spot, shows how often I use that feature lol.

Fixed for the next release.
