### ISSUE TITLE
Tooltips are MIA from the reply and edit pages

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#291]
**Describe the bug**  
The Tooltips are missing when you try to reply or edit something

**Steps to Reproduce**  
1. Go to a post
2. Click on click on reply
3. Look press on Bold, Italics, etc

**Expected behavior**  
A tooltip should inform you what each is

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: [e.g. v22.5.20]
 - Sync variant: [e.g. pro]

**Additional context**

**Comment by laurencedawson** [comment]
Nice idea. Added for the next release.
