### ISSUE TITLE
Translate option does not appear on image posts with a body

### ISSUE THREAD

**Issue by SaintWacko** [laurencedawson/sync-for-lemmy#292]
**Describe the bug**  
In lemmy, unlike reddit, it is possible to make an image post that also has a text body. When subscribed to Ultra, the translate option does not appear on these posts.

**Steps to Reproduce**  
1. Find an image post with a text body (ex. https://mlem.a-smol-cat.fr/post/89169)
2. Press the options menu button on the post
3. Witness the lack of translate button

**Expected behavior**  
As with pure text posts, this type of post should have a translate button in the options

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - Android: 13
 - Sync version: 23.08.03-16:15(27)
 - Sync variant: Ultra

**Comment by laurencedawson** [comment]
Fixed for the next release.
