### ISSUE TITLE
The app should give a dialog asking if you want to leave when you cancel a submit

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#294]
Currently when you go to submit a post, and you try to go back, it goes back and would be nice if it asked you to confirm if you had made changes to the post and it wasn't blank

**Comment by laurencedawson** [comment]
It currently does this for the text field submission. Did you want this for title + url too?

**Comment by corylowry12** [comment]
I think so. I was thinking it would be best to have it for all types of submissions as long as theres something in the text boxes.

**Comment by laurencedawson** [comment]
Good shout. Added.
