### ISSUE TITLE
NSFW status doesn't display in Post View 

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#296]
**Describe the bug**  
In feed view it shows NSFW status but not in post view 

**Steps to Reproduce**  
1. Go to a Sync 
2. Click on a NSFW post
3. See error

**Expected behavior**  
NSFW status should display next to the post title

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: [e.g. v22.5.20]
 - Sync variant: [e.g. pro]

**Additional context**

**Comment by laurencedawson** [comment]
Post view? Like in comments?

**Comment by pwd-github** [comment]
> Post view? Like in comments?

Yep. Click here for example, there's no indication that it's a NSFW post: https://lemmy.tf/post/715026

**Comment by laurencedawson** [comment]
Gotcha. The logic for this was, once you've clicked it you already know its nsfw lol

**Comment by laurencedawson** [comment]
Closing as this is expected behaviour.
