### ISSUE TITLE
Post Editing doesn't let you change anything except text 

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#297]
**Describe the bug**  
On Lemmy you can edit the title, the URL/image, text and NSFW status, this is missing 

**Steps to Reproduce**  
1. Go to a post you posted
2. Click on edit
3. See error

**Expected behavior**  

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: [e.g. v22.5.20]
 - Sync variant: [e.g. pro]

**Additional context**

**Comment by laurencedawson** [comment]
Fixed for the next release.
