### ISSUE TITLE
Block button does not change to "Unblock" when you block a community 

### ISSUE THREAD

**Issue by Spliffman1** [laurencedawson/sync-for-lemmy#300]
**Describe the bug**  
When I go to community info and hit the Block button it blocks the community, but the Block button continues to say Block.. Seems like it should change to "Unblock" to indicate the community is actually blocked 

**Steps to Reproduce**  
1. Go to 'a community about page ..'
2. Click on 'Block' button 
3.Click block button on pop up window bottom right 
4. See error original button still says Block 

**Expected behavior**  
I would expect the button to change to say Unblock, or some indication that the community is blocked 

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: Oneplus 11
 - Android: 13
 - Sync version: [e.g. v22.8.03-16:15 (27)
 - Sync variant: ultra 

**Additional context**

**Comment by laurencedawson** [comment]
Fixed.
