### ISSUE TITLE
The input box types are mismatched? Title thinks it's a URL and URL think it's a title 

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#303]
**Describe the bug**  
The input box types are mismatched? Title thinks it's a URL and URL think it's a title

**Steps to Reproduce**  
1. Go to create a new post
2. Click on title 
3. Type consecutive words
4. Click on URL
5. Type consecutive words
6. See error

**Expected behavior**  
URL should be spell checking and Title should add spaces after words automatically

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: beta 29
 - Sync variant: [e.g. pro]

**Additional context**

**Comment by laurencedawson** [comment]
Good spot, fixed.
