### ISSUE TITLE
Wording not consistent when subscribing to community

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#307]
The Join bottom sheet should say subscribe instead of join to match the chip

![Screenshot_20230813_213155_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/8837361/1fcd1d4c-9ff1-4daf-88f5-a06dfb1bd122)

**Comment by laurencedawson** [comment]
Good catch. Fixed.
