### ISSUE TITLE
Input type on instance field in Add Account isn't good for domain names

### ISSUE THREAD

**Issue by brad-anderson** [laurencedawson/sync-for-lemmy#31]
**Describe the bug**  
If you are typing in a domain name into the instance field on the Add Account screen, auto correct is enabled meaning you have to go fixup what you typed to get the domain name you intended.

**Steps to Reproduce**  
1. Go to Add Account
2. Type "autocorrekt.com"
3. Domain typed will be changed to "autocorrect.com"

**Expected behavior**  
Domains aren't good targets for autocorrect so it should just take what is typed verbatim.

**Screenshots**  
N/A

**Smartphone (please complete the following information):**
 - Device: Samsung S21 Ultra
 - Keyboard: SwiftKey
 - Android: 13
 - Sync version: v23.07.24-19:51
 - Sync variant: Internal

**Comment by laurencedawson** [comment]
Fixed
