### ISSUE TITLE
Allow to automatically set title for link posts, like web ui does.

### ISSUE THREAD

**Issue by snaggen** [laurencedawson/sync-for-lemmy#311]
**Is your feature request related to a problem? Please describe.**  
In the web ui, when you post a link, you get a preview of the title below the link field with the option to set that as the title with one click. This is a really nice feature which would be great to get in Sync as well. 

**Describe the solution you'd like**  
Pretty much the same as in the web ui, when you fill in the URL field, it fetches the title and displays that below the URL box. And if you click on that, it populates the Title box with that.

**Comment by pwd-github** [comment]
![Screenshot_20230814-074913](https://github.com/laurencedawson/sync-for-lemmy/assets/203217/77ff3838-b6e4-41de-96b2-52e1dc286abf)

This is already hooked up, press the grey galaxy stars on the right side of the title box and it fills in the title text

**Comment by snaggen** [comment]
Sorry for the noise then, just me not noticing the stars and understanding what they meant... I will close this.
