### ISSUE TITLE
Posting: Community selector shows communities I filtered/blocked

### ISSUE THREAD

**Issue by Coffee-Viking** [laurencedawson/sync-for-lemmy#313]
**Describe the bug**  
When starting a new post from the frontpage (no active community selected), clicking into the field "community" shows a list of recently visited, moderated and favorite communities. However some of the recently visited ones are communities I have blocked from browsing /everything/new, hence they are recent visits but absolutely not places I'd want to post in.

**Steps to Reproduce**  
1. Go to Submit
2. Click on Community
3. See blocked communities in list

**Expected behavior**  
I'd expect blocked communities to be filtered out.

**Screenshots**  

**Smartphone (please complete the following information):**
Device independent

**Comment by laurencedawson** [comment]
Good spot, fixed for the next release.
