### ISSUE TITLE
[Ultra] Extract Text From Images for Post Title

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#315]
**Is your feature request related to a problem? Please describe.**  
Add the ability to pull text from images for titles

**Describe the solution you'd like**  
The ability to pull text from images for titles 

**Describe alternatives you've considered**  
None 

**Additional context**  
When you want to post a screenshot or meme, this can be a lifesaver. Or save you 20 seconds, whichever sounds less dramatic

**Comment by laurencedawson** [comment]
Great idea. Added for the next release.
