### ISSUE TITLE
Can't Share Images To Sync

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#32]
**Describe the bug**  
When you try and share images to sync, it sucks

**Steps to Reproduce**  
1. Go to your gallery 
2. Select an image
3. Share to sync
4. Fail

**Expected behavior**  
It should say community rather than subreddit
It should present a list of communities I subscribe to
It should fill out the rest is I start typing a community name 

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: [e.g. v22.5.20]
 - Sync variant: [e.g. pro]

**Additional context**

**Comment by kringger** [comment]
Happens with links too. Suggesting titles works, but the community picker doesn't populate a list of subscribed communities and attempting to submit hangs on "submitting"

![Screenshot_20230724-222358.png](https://github.com/laurencedawson/sync-for-lemmy/assets/35173157/9db68c77-7371-4431-b33a-80e482b604d3)

**Comment by laurencedawson** [comment]
New posting isn't yet available.

https://github.com/laurencedawson/sync-for-lemmy/issues/37
