### ISSUE TITLE
Emote filter is also filtering regular embedded pictures

### ISSUE THREAD

**Issue by Coffee-Viking** [laurencedawson/sync-for-lemmy#321]
**Describe the bug**  
When disabling the swatch "show emote pictures", Sync will also deactivate potentially wanted embedded pictures.

**Steps to Reproduce**  
1. Disable emotes in settings
2. Open https://lemmy.world/post/3193108 (example)
3. Scroll down to the "edit" 
4. See: An official statement has been made (emote)
5. Enable emotes in settings
6. Realize it's not an emote at all

**Expected behavior**  
Differentiate between emotes and regular embeds.

However this will be hard to achieve, since the path to the picture is just a random link to the instances' picture folder.

**Screenshots**  
https://imgur.com/a/YOlWru9

**Smartphone (please complete the following information):**
 - Sync version: Beta 30
 - Sync variant: Ultra

**Additional context**

**Comment by laurencedawson** [comment]
I've renamed the setting to "hide embedded images" to better highlight this.
