### ISSUE TITLE
Add option to blur NSFW previews 

### ISSUE THREAD

**Issue by Joristdh** [laurencedawson/sync-for-lemmy#323]
**Is your feature request related to a problem? Please describe.**  
Currently it is only possible to fully block NSFW previews.

**Describe the solution you'd like**  
Allow an option for blurred NSFW previews instead of fully opaque red. 

**Describe alternatives you've considered**  
You can fully hide the previews, but this gives large jarring red previews. Blurred previews would still hide the NSFW content, but not stand out as much.

**Additional context**  
I vaguely remember that this discussion was also held for Sync for Reddit and the response then was that it was too resource intensive. However, phones have become more powerful and it could be optional. Other Lemmy apps much as Connect & Summit and Web UIs already blur previews.

**Comment by laurencedawson** [comment]
Replaced red previews for blur in the next release.
