### ISSUE TITLE
Reappearing hidden posts, app scrolls up automatically.

### ISSUE THREAD

**Issue by wason-sonico** [laurencedawson/sync-for-lemmy#324]
**Describe the bug**  
When going back to the feed, from a post, when I start scrolling the app will suddenly bring back hidden posts and scroll up automatically.
I have to press the hide read FAB button to hide them again and continue where I was.

**Steps to Reproduce**  
1. Scroll through posts, posts are marked as read automatically.
2. Somehow read posts will also appear in the feed as I scroll.
3. Press the "hide read" FAB.
4. Open a post.
5. Go back.
6. Try to scroll.
7. The feed will move up with all previously hidden posts now visible again.

**Expected behavior**  
Once you hide a post it should stay hidden unless you reload (or reopen the app). I'm assuming the autoscroll up is because the hidden posts appear suddenly again.
I have the "Show read posts" enabled on my Lemmy account settings (server settings).

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi K40 Gaming
 - Android: 13
 - Sync version: v23.08.12-23:05
 - Sync variant: Sync for Lemmy

**Additional context**  
Something to note is that this issue was also present on Sync for Reddit.

**Comment by laurencedawson** [comment]
Scrolling up automatically was by design though.
