### ISSUE TITLE
Post with embedded images reloads them every time they scroll into view

### ISSUE THREAD

**Issue by sethkinast** [laurencedawson/sync-for-lemmy#325]
**Describe the bug**  
https://lemmy.ml/post/3412121

This post has 20+ inline embedded images. When you scroll past them to the comments and then scroll back up, the page jumps to a different scroll location because the images seem to be unloaded and reloaded.

**Steps to Reproduce**  
1. Go to https://lemmy.ml/post/3412121
3. Scroll down to the comments
4. Scroll back up and see page jump around as the images blip in and out 

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android: 13
 - Sync version: beta 30

**Comment by donnielrt** [comment]
I was just going to open an issue using the same Lemmy post! The issues are particularly pronounced on that post, and Sync is pretty unusable on it.

Samsung S10e Android 12, beta 30.

**Comment by laurencedawson** [comment]
Merging with #328.
