### ISSUE TITLE
Ability to auto play mp4 clips in posts 

### ISSUE THREAD

**Issue by Spliffman1** [laurencedawson/sync-for-lemmy#327]
Right now short MP4 clips on posts only show gray square which you have to tap to open and play. 

I noticed they autoplay on Liftoff and Voyager.. Others preview the image with tap to play. Would it be possible to support autoplay on Sync? 

![Screenshot_2023-08-16-10-45-32-60_74ab5dcdef147bb53a2c1aad56578295](https://github.com/laurencedawson/sync-for-lemmy/assets/141503240/9bd4bde4-8bba-46c7-9cf0-9107883ff4b2)
![Screenshot_2023-08-16-13-32-18-93_f8c215a6f14c21709a2994385a7dc495](https://github.com/laurencedawson/sync-for-lemmy/assets/141503240/6e8a1ea4-201e-4429-a9e4-3ee7c62c72dc)

Screenshots show same post from Liftoff where image autoplays, on Sync only the grey square. 
Would be a nice addition if possible

**Comment by laurencedawson** [comment]
Duplicate, merging:

https://github.com/laurencedawson/sync-for-lemmy/issues/164
