### ISSUE TITLE
Search All leads to a 404

### ISSUE THREAD

**Issue by GittyMac** [laurencedawson/sync-for-lemmy#33]
**Describe the bug**  
Search All leads to a 404, seemingly trying to connect to Cloudflare. If you try to search again, there's a TODO toast.

**Steps to Reproduce**  
1. Go to 'Explore'
2. Type in a search query.
3. Click 'Search All'

**Expected behavior**  
There should be a search result much like on /search in the web, or if the feature is unfinished, there should be a TODO toast with no effect.

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - Android: 14 Beta 4
 - Sync version: v22.07.24-19:51
 - Sync variant: Internal

**Additional context**  
I was using an account on to the lemm.ee instance.

**Comment by laurencedawson** [comment]
Expected as its not yet hooked up:

https://github.com/laurencedawson/sync-for-lemmy/issues/14
