### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Limess** [laurencedawson/sync-for-lemmy#332]
**Describe the bug**  
Unable to login to any instance (tried feddit.uk, lemmy.world

**Steps to Reproduce**  
1. Create any account on instance, use 1password to mint 100 character password (tried all alphanumeric and with symbols)
2. Attempt to add account on sync for Lemmy. Tried with pasting password, autofill with 1password, changing username (limes, `@limes`, my email)
3. See "invalid login"

**Expected behavior**  
Login succeeds

**Screenshots**  
![Screenshot_20230818-085627.png](https://github.com/laurencedawson/sync-for-lemmy/assets/3199181/4de801e6-0942-45ae-af98-dc3689b9e997)

![Screenshot_20230818-085618.png](https://github.com/laurencedawson/sync-for-lemmy/assets/3199181/10de0058-c582-4979-b479-06a38f69302c)

![Screenshot_20230818-085627.png](https://github.com/laurencedawson/sync-for-lemmy/assets/3199181/514178fd-f852-4a40-9ce4-024a5e3b490f)

![Screenshot_20230818-085859.png](https://github.com/laurencedawson/sync-for-lemmy/assets/3199181/b383ebe7-08b4-4dd9-bd11-4bf913aab549)

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - Android: 13
 - Sync version: v23.08.12-23.05 (29)
 - Sync variant: [e.g. pro]

**Additional context**  
I can't login successfully at all, so I'm not sure how to reproduce consistently for others.

**Comment by Limess** [comment]
Sorry about the screenshot order, I'm only able to submit on mobile right now.

The intention was to show 

* I have a valid account on feddit.uk
* How I used 1password autofill
* The error message

**Comment by pwd-github** [comment]
Shorten your password. IIRC, 30 should be the limit

**Comment by Limess** [comment]
Thanks! Both Lemmy instances seemed to accept the full 100 characters, I guess there's some truncation going on which is then causing issues.

I shortened to 60 characters after some googling and this now works.
