### ISSUE TITLE
No messages returned snackbar doesn't automatically go away

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#333]
No messages returned snackbar doesn't go away when going to another tab 

![Screenshot_20230818_192545_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/8837361/559bc274-c7fb-4986-a903-e6ef28ded7f7)

**Comment by laurencedawson** [comment]
Unable to reproduce this one...

**Comment by corylowry12** [comment]
Unable to reproduce anymore, closing for now
