### ISSUE TITLE
Cannot restore purchase from sync dev

### ISSUE THREAD

**Issue by abs3ntdev** [laurencedawson/sync-for-lemmy#335]
**Describe the bug**  

I purchased sync ultimate lifetime on sync dev and cannot restore it in this app

**Steps to Reproduce**  
1. Purchase ultimate lifetime in sync dev
2. Attempt to restore purchase in sync for lemmy

**Expected behavior**  

The purchase successfully restores

**Screenshots**  

![Screenshot_20230819_180621_Sync.png](https://github.com/laurencedawson/sync-for-lemmy/assets/86447830/3d2c2a9b-d3f3-4101-909e-170d1aeaebc2)

**Additional context**

**Comment by kontrastylez** [comment]
These are two completely different applications, also in Play Store. Restoring will not work because of this.

**Comment by abs3ntdev** [comment]
Yeah I'm aware they are different apps. Are we expected to pay for lifetime again? I assumed the sync ultra lifetime purchase would be respected in the new client.

**Comment by pwd-github** [comment]
Sync for Reddit Ultra Lifetime was for the duration of Sync for Reddit, which is now dead. 

Sync for Lemmy is a new app. Even if LJ wanted to transfer purchases, he couldn't. But this is his new venture and he hopes it's successful. New app, new platform, new goals. As such, it requires a new purchase.

**Comment by abs3ntdev** [comment]
I mean it's for sure possible to transfer lifetime purchases over, but sounds good. I really cannot justify dropping another 100 dollars in addition to the money I already spent. Disappointing. I'll close the issue then.
