### ISSUE TITLE
"Blocked posts due to filters" should have more information 

### ISSUE THREAD

**Issue by donnielrt** [laurencedawson/sync-for-lemmy#336]
**Is your feature request related to a problem? Please describe.**  
I use blocking/filtering extensively to curate my feed, but I'm now running into a problem because of it. In my feed, I'm repeatedly seeing the error about blocked posts due to filters. I see this message many times a minute, and often have to hit retry 3-4 times before any new posts appear.

I have quite a few filters/blocks, but this still seems surprising to me.

![Screenshot_20230820-144528_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/1524374/9c1dbcd8-e96f-4b4b-8f51-12bbcb534ca6)

**Describe the solution you'd like**  
It would be useful if I could see which posts have been blocked by which filters to make sure I haven't accidentally made them too broad. Perhaps a "more info" link or something?

**Describe alternatives you've considered**  
Disabling all filters. I've tried this in effect by visiting Lemmy on another client or different account on Sync.

**Additional context**  
Add any other context, screenshot(s) or video(s) about the feature request here.

**Comment by laurencedawson** [comment]
What should it display? 

The reason you're encountering this is due to the filters being applied locally. Hitting "retry" loads the next page of posts.

Maybe instead of retry it should be "next page"?

**Comment by laurencedawson** [comment]
I've beefed this up for the next release.

**Comment by donnielrt** [comment]
> What should it display?
> 

The specific problem I was running into is not knowing if there's a problem in my filter settings or not. I'm seeing the banner popup frequently, and sometimes hitting retry immediately shows the banner again with no new posts, and I have to hit retry up to 7-8 times to see any new posts. This seems like some sort of error (either with overly broad filters, or a bug).

What I was hoping for was a way to see _which_ posts have been blocked, by _which_ filters. This will help me diagnose the issue. One way I can imagine this is a button on the banner that shows blocked posts or something.

In any case, I'll wait for the next update to see if the issue has been resolved :) thanks!
