### ISSUE TITLE
Disable infinite scroll

### ISSUE THREAD

**Issue by fillwithjoy1** [laurencedawson/sync-for-lemmy#337]
**Is your feature request related to a problem? Please describe.**  
Infinite scroll isn't good for one reason and that's because you do not get any indicator on how much time you spend on the app 

**Describe the solution you'd like**  
The ability to just toggle off infinite scrolling to something like 10 posts per page or something similar like that

**Describe alternatives you've considered**  
I haven't considered any alternatives but I haven't found this in the settings

**Additional context**  
Add any other context, screenshot(s) or video(s) about the feature request here.
Nothing else

**Comment by laurencedawson** [comment]
As with S4R I don't intend to add this. You can enable dividers between pages to help you keep track of what page you're on though:

Settings > Post options > Display page dividers
