### ISSUE TITLE
Missing audio on Redgifs posts

### ISSUE THREAD

**Issue by Monsoon4767** [laurencedawson/sync-for-lemmy#339]
**Describe the bug**  
Around half of the redgifs posts I see show no audio in Sync, but when I open the same post in [Infinity](https://codeberg.org/Bazsalanszky/Eternity) or on redgifs directly there's audio.

**Steps to Reproduce**  
- [Sample post (warning: NSFW / nudity)](https://lemmynsfw.com/post/1139253)

**Expected behavior**  
The media will play with audio

**Screenshots**

![Screenshot_20230822-232008_Sync (1)](https://github.com/laurencedawson/sync-for-lemmy/assets/114372101/538776e1-4299-4d8c-8bc6-4e5d6f150ab9)

**Smartphone (please complete the following information):**
 - Device: Zenfone 9
 - Android: 13
 - Sync version: version v23.08.12-23:05
 - Sync variant: Default

**Additional context**  
I noticed Sync loads the media from `api.redgifs.com` while Infinity loads from `thumbs44.redgifs.com` and includes some kind of signature query param.

**Comment by laurencedawson** [comment]
This has been fixed in the latest version. Cheers.
