### ISSUE TITLE
Share -> post comment generates reddit link.

### ISSUE THREAD

**Issue by Coffee-Viking** [laurencedawson/sync-for-lemmy#34]
**Describe the bug**  
When trying to share a link to the post comments, instead of the lemmy instance, reddit.com/ is placed as a link.

**Steps to Reproduce**  
1. Go to any random post
2. Click on share
3. Select post comments

**Expected behavior**  
Share the exact lemmy instance comment section.

**Screenshots**  
https://imgur.com/a/LT9gngV

**Smartphone (please complete the following information):**
 Device independent.

**Comment by NomNuggetNom** [comment]
This also applies to Copy > Copy Permalink

**Comment by laurencedawson** [comment]
Fixed
