### ISSUE TITLE
Deep linking causes a transparent, unresponsive Activity to appear if Sync isn't already running

### ISSUE THREAD

**Issue by zacharee** [laurencedawson/sync-for-lemmy#345]
**Describe the bug**  
If Sync isn't currently running, tapping a supported link opens a transparent and unresponsive Activity that never finishes or loads the link.

**Steps to Reproduce**  
1. Make sure Sync isn't in Recents.
2. Enable `lemmy.world` to open in Sync.
3. Send `https://lemmy.world/post/3688392` in Discord.
4. Tap the link.
5. It will look like nothing has happened and the screen isn't responding to touches, but if you go into Recents you'll see a blank Activity from Sync.

**Expected behavior**  
The Activity should launch the link in Sync.

**Smartphone (please complete the following information):**
 - Device: Galaxy S23 Ultra
 - Android: 14
 - Sync version: beta 34
 - Sync variant: Ultra

**Additional context**  
At a guess, I think the following block of code in `HomeActivity` might be the issue:

```
if (!isTaskRoot()) {
    finish();
    overridePendingTransition(0, 0);
    return;
}
```

I think `isTaskRoot()` is going to return false here, since it was launched from `IntentActivity` and `IntentActivity` didn't call `finish()`, which would short-circuit the logic, finish `HomeActivity`, and leave the transparent `IntentActivity` up.

The logs do show that `HomeActivity` gets destroyed after tapping the link, and since that's the only place `finish()` is called inside `HomeActivity` aside from a failed biometric auth (which I don't have enabled) is in that block, I think it could be the cause.

**Comment by zacharee** [comment]
As another datapoint, if I launch `HomeActivity.{Variant}` directly with a URL in the `link` extra, it works fine: https://github.com/zacharee/MastodonRedirect/commit/d6cae0e2e6b9b8b356f04015692fbbdad5271811.

**Comment by laurencedawson** [comment]
Fixed.
