### ISSUE TITLE
Viewing comment from Inbox doesn't scroll to comment

### ISSUE THREAD

**Issue by dinosoeren** [laurencedawson/sync-for-lemmy#346]
**Describe the bug**  
Viewing comments' context from my Inbox doesn't scroll to the comment on the post.

**Steps to Reproduce**  
1. Go to 'Inbox'
2. Click on any comment reply
3. Observe it remains at the top

**Expected behavior**  
It should scroll immediately to the relevant context, automatically.

**Screenshots**  
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - Android: 13
 - Sync version: V23.08.23-18:29 (34)
 - Sync variant: free

**Additional context**  
I tried this with multiple different comments on the same post. I considered maybe the comment or its context was deleted -- can the app please indicate it as such, in that case?

**Comment by laurencedawson** [comment]
Fixed for the next release.
