### ISSUE TITLE
Tasker Integration: Action Configuration Broken & No Post Syncing 

### ISSUE THREAD

**Issue by lemmonade2023** [laurencedawson/sync-for-lemmy#350]
User is unable to save an action settings in the action configuration screen in Tasker. 

Action only shows <???>

Other Issues:
- Label still says subreddit instead of community
- action doesn't show details after save
- when running action there is no error message shows as successful
- no post syncing occurs

Relevant Feature Requests
- be able to browse subscribed community when configuring action
- select which account to sync in configuration screen
- be able to configure syncing image and videos posts vs text only

**Comment by laurencedawson** [comment]
Completely forgot about this feature, I might sadly drop it...

**Comment by laurencedawson** [comment]
Sorry to say this has been removed in the current version.
