### ISSUE TITLE
Profile button in List View just a TODO

### ISSUE THREAD

**Issue by seamuslowry** [laurencedawson/sync-for-lemmy#354]
**Describe the bug**  
If you are using List View, the button that should take you to the poster's profile just puts up a TODO toast.

**Steps to Reproduce**  
1. Change post view type to List
2. Expand actions for any post
3. Click on profile button
4. See 'TODO' in a toast

**Expected behavior**  
Clicking that button should instead take you to the poster's profile

**Screenshots**  
![Screenshot_20230825-141558.png](https://github.com/laurencedawson/sync-for-lemmy/assets/6394062/c59c5b70-35ab-4ccd-99da-c94486de9d49)

![Screenshot_20230825-142129.png](https://github.com/laurencedawson/sync-for-lemmy/assets/6394062/1f57a88c-dca4-440e-8f7e-98abd42c21ce)

**Smartphone (please complete the following information):**
 - Device: Pixel Fold
 - Android: 13
 - Sync version: v28.08.23-18:29 (34)
 - Sync variant: pro

**Comment by laurencedawson** [comment]
Fixed for the next release.
