### ISSUE TITLE
Card options (columns) missing in View Type Settings menu when view is set to Small Cards

### ISSUE THREAD

**Issue by applesandsynths** [laurencedawson/sync-for-lemmy#355]
Card options (columns) missing in Settings > View Type menu when view is set to Small Cards

If I change view type to Cards, I can then specify number of columns which carries over when I switch view type to Small Cards, yet I can no longer change columns again without switching back to regular Cards view first 

**Steps to Reproduce**  
1. Set View Type to Cards
2. Set columns to 2
3. Change view type to Small Cards
4. Notice how "Card Options" menu along with columns adjustment settings disappears 
5. Switch to Cards view type,and option for columns comes back. 

**Expected behavior**  
Columns should be a visible option for small cards and smaller cards view type

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Z Fold 4
 - Android: 13
 - Sync version:  23.08.25-12:16 Beta 40
 - Sync variant: regular

**Comment by laurencedawson** [comment]
This was a design choice I'm afraid, only large cards are eligible for multi column. I might add slide support too soon.
