### ISSUE TITLE
Disabling "mark posts as read" does not work

### ISSUE THREAD

**Issue by ziddey** [laurencedawson/sync-for-lemmy#356]
**Describe the bug**  
After disabling "mark posts as read," posts are still being marked as read.

**Steps to Reproduce**  
1. Go to Settings > History
2. Disable "Mark posts as read"
3. Go to feed and select any unread post
4. Go back to feed and refresh
5. See that post is now marked as read

**Expected behavior**  
Posts should never become marked read if the option is disabled.

**Screenshots**  

https://github.com/laurencedawson/sync-for-lemmy/assets/3846501/7d40f8d6-20c1-4791-a55c-9c6987cd167a

https://streamable.com/y2c6ez

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - Android: 14
 - Sync version: v23.08.25-12:16
 - Sync variant: free

**Additional context**  
Instead of refreshing the feed, if the post is viewed a second time, it will be also be marked as read on returning to the feed.

**Comment by laurencedawson** [comment]
OK this is a strange one.  So lemmy marks posts as read remotely...

If you view a post its marked as read even if sync doesnt tell the instance to mark it as read.

Removing the options for now as this is no longer used.
