### ISSUE TITLE
Pressing About at Root (Everything, Local, Subscribed) should fetch info from the sidebar

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#39]
**Describe the bug**  
Pressing about should show the sidebar information on the website

**Steps to Reproduce**  
1. Go to local
2. Click on the action button
3. Press about
4. Get lied to

**Expected behavior**  
It shows sidebar information

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: [e.g. v22.5.20]
 - Sync variant: [e.g. pro]

**Additional context**

**Comment by laurencedawson** [comment]
Do you mean the instances sidebar?

**Comment by pwd-github** [comment]
> Do you mean the instances sidebar?

I do indeed

**Comment by laurencedawson** [comment]
This has since been added!
