### ISSUE TITLE
When viewing comments in your own or someone else's profile, and then clicking on one of the comments, getting error message, instead of taking me to that comment in the post that it was made in

### ISSUE THREAD

**Issue by gazelle8844** [laurencedawson/sync-for-lemmy#401]
**Describe the bug**  
When viewing your own, or someone else's profile, and you go to their comments, and you click on a comment, it is giving me an error message "could not load post".

**Steps to Reproduce**  
1. Go to your own or someone else's profile
2. Click on comments
3. Click on one of the comments
4. Get an error message saying "could not load post"

**Expected behavior**  
When clicking on a comment in someone's profile, it should take you to that comment, in the post it was made in.

**Screenshots**  
Go to someone's profile or your own, and select comments.

![Screenshot_20230829_161955_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/102678194/9e9cbb74-3c9d-40ef-b9b1-587139a27157)

Tap on one of the comments

![Screenshot_20230829_162040_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/102678194/38b63bfa-b6fa-4e4c-a0d0-bc6c659384f6)   

It gives an error message "could not load post"   

![Screenshot_20230829_162102_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/102678194/59d7d287-26db-4335-8110-43ec1240d121)

**Smartphone (please complete the following information):**
 - Device: Samsung A53 5G  (can also reproduce on my Samsung S7 tablet )
 - Android: 13
 - Sync version: V23.08.29-02:02 (44)
 - Sync variant: internal beta

**Additional context**

**Comment by corylowry12** [comment]
Same for me

**Comment by laurencedawson** [comment]
Fixed.
