### ISSUE TITLE
The article summarizer in Ultra does not show "Summary " when using "Slides" view type and "Show image previews" turned off

### ISSUE THREAD

**Issue by ghost** [laurencedawson/sync-for-lemmy#409]
**Describe the bug**  
When using Slides view type and have "Show image previews" turned off, "Summary" does not show up, and I'm not able to access the article summarizer (Ultra feature). When I turn the " Show image previews" on, I am then able to see it.

**Steps to Reproduce**  
1. Change view type to Slides
2. In Settings>View type>turn off "Show image previews"
3. Go find some news articles
4. Unable to see "Summary", so I cannot view the article summarizer

**Expected behavior**  
To be able to see "Summary", and view the article summarizer, with the "Show image previews" turned off.

**Screenshots**  

Use Slides view type and turn off  "Show image previews"   

![Screenshot_20230830_053045_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/102678194/5b3e97a1-25f6-4bb6-91f0-16bd7f8e9867)

This is how an article looks. There is no "Summary", and unable to view articles summarizer   

![Screenshot_20230830_052915_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/102678194/6cd95fdd-f2e7-46a6-b608-0db0d5c02866)   

![Screenshot_20230830_060223_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/102678194/d712bce0-7c72-4724-832a-10d05c260f4e)

Here is how the same article looks with the "Show image previews" turned on, you are able to click on "Summary" and view the article summarizer   

![Screenshot_20230830_053849_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/102678194/68ec0859-6fe3-426f-9042-4f0ec99f3463)   

![Screenshot_20230830_052740_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/102678194/e6de4279-c840-456c-ac86-8163ba7d27bd)

**Smartphone (please complete the following information):**
 - Device: Samsung A53 5G
 - Android: 13
 - Sync version: v23.08.30-03:06 (47)
 - Sync variant: internal beta

**Additional context**  
It seems that the only way to view the article summarizer is to use either the Slides view, with the "Show image preview" turned on, or the Cards view. Is this the intended behavior?

**Comment by laurencedawson** [comment]
Added to the "post options" bottomsheet.
