### ISSUE TITLE
Share text post link generates null pointer.

### ISSUE THREAD

**Issue by Coffee-Viking** [laurencedawson/sync-for-lemmy#41]
**Describe the bug**  
When trying to share a link to a text post from either the frontpage or within the opened post, the resulting link is "null".

**Steps to Reproduce**  
1. Go to any random text only post
2. Click on share
3. Select "link"

**Expected behavior**  
A link to the full url on the respective lemmy instance.

**Screenshots**  
https://imgur.com/a/qyrFiDY

**Smartphone (please complete the following information):**
 Device independent

**Comment by laurencedawson** [comment]
Can't reproduce this. Possibly fixed.

**Comment by Coffee-Viking** [comment]
@laurencedawson confirmed fixed, probably along with one of the other null-thingies.
