### ISSUE TITLE
[Ultra] Feature extension: Summarize third party articles

### ISSUE THREAD

**Issue by Coffee-Viking** [laurencedawson/sync-for-lemmy#416]
The current article summarizer works great for anything posted on Lemmy, but it would be neat being able to use the feature for articles posted elsewhere without having to post them to Lemmy first.

i.e. Go to news aggregator of choice -> click on link -> share -> select Sync for Lemmy as target -> have summarized article load on screen

Ideally with the option to send a bunch of articles and then being able to read them one after another, either attach the second one below with a horizontal divider, or having a "next" button/swipe action to flip pages.

**Comment by laurencedawson** [comment]
Added for the next release!
