### ISSUE TITLE
Some posts don't display all comments

### ISSUE THREAD

**Issue by chloyster** [laurencedawson/sync-for-lemmy#42]
**Describe the bug**  
On some posts, not every comment is displayed, and the nesting ends up looking odd. These threads usually crash as well

**Steps to Reproduce**  
1. Go to a certain post (happens for me on this one for example https://lemmy.blahaj.zone/post/1227917
2. Not everything seems to load, and the nesting looks skewed due to it
3. Scroll down a bit and usually a crash occurs

**Expected behavior**  
Things load properly, the nesting looks normal, and the app doesn't crash

**Screenshots**  
![screen-20230724-144054~2_1.gif](https://github.com/laurencedawson/sync-for-lemmy/assets/15004447/65357a5e-a3ac-4997-8fdf-0083b58e9749)

**Smartphone (please complete the following information):**
 Sync version: v23.07.24-19:51    
 Sync flavor: googlePlay
 View type: Smaller cards    
 Model: Google Pixel 6 Pro    
 Android: 13

**Additional context**  
I had quite a few changes to the settings. I can go into more details on this if needed

**Comment by kringger** [comment]
I noticed this on the web UI earlier today, so this might be related to the recent lemmy.world issues

**Comment by laurencedawson** [comment]
Merging with:

https://github.com/laurencedawson/sync-for-lemmy/issues/44
