### ISSUE TITLE
[Minor] Ultra: Inconsistent wording

### ISSUE THREAD

**Issue by Coffee-Viking** [laurencedawson/sync-for-lemmy#422]
**Describe the bug**  
In case you've tagged and highlighted a user, you will have "remove highlight" and "remove tag" options when selecting the respective user again.

However "remove highlight" opens an edit dialogue (where a remove button is located) while "remove tag" simply removes the tag.

To add consistency, I'd suggest to either...

1. Rename "remove highlight" to "edit/remove highlight" (quick fix)
2. Replace the highlight editor with an actual remove only function and then leave it to the user to add another one, if that was the intention
3. Add a tag editor and rename both functions to "edit/remove" tag & highlight

**Comment by laurencedawson** [comment]
I've redone this to make the two consistent. Cheers.
