### ISSUE TITLE
Search bar for instance list

### ISSUE THREAD

**Issue by AGuyNamedRakkun** [laurencedawson/sync-for-lemmy#430]
**Is your feature request related to a problem? Please describe.**  
Not much of a problem but I think having a search bar for instances would be a nice QoL thing 

**Describe the solution you'd like**  
Having a search bar for instance list at the top, enabling users to search for the instances in the list instead of scrolling it until they find their desired instance since there are too many instances.

**Comment by laurencedawson** [comment]
Added for the next release.
