### ISSUE TITLE
Compact View Images Fail to Load First Try

### ISSUE THREAD

**Issue by Masterjts** [laurencedawson/sync-for-lemmy#440]
**Describe the bug**  
A stand alone image uploaded to a lemmy instance will fail to load when opened (from compact view mode) resulting in an infinite load screen until you press back. Upon pressing back the imagine will load for a split second before returning you to the thread list. If opened a second time the image will instantly load. Holding quick preview on the image will load the image and when the image is then opened from the thread list it will open properly.

**Expected behavior**  
I expect the image to open correctly when clicked from the thread list.

**Smartphone (please complete the following information):**
Samsung Galaxy S20 FE 5G
Android 13, One UI 5.1

**Comment by laurencedawson** [comment]
Latest update fixes this.
