### ISSUE TITLE
Crash on startup with latest update

### ISSUE THREAD

**Issue by mittensicle** [laurencedawson/sync-for-lemmy#445]
**Description**
Crash on startup after opening the app after a few seconds with the latest update, fixes when storage and cache are wiped, returns when I load the backup from cloud or storage. Something about my current settings isn't compatible with the latest update.

**Steps to Reproduce**  
1. open app and it crashes
2. clear cache and storage, log in again and it works
3. load my specific settings, crash

**Expected behavior**  
No crash.

**Smartphone**
 - Device: Pixel 6 Pro
 - Android: 13
 - Sync version: v23.09.19-20:43
 - Sync variant: Ultra

**Comment by laurencedawson** [comment]
Closing as I'm 99% sure this was fixed with the recent updates.
