### ISSUE TITLE
App crash when changing views in the inbox from left drawer

### ISSUE THREAD

**Issue by momnom** [laurencedawson/sync-for-lemmy#446]
**Describe the bug**  
When navigating to a different view of the inbox (from inbox drop-down button) the app will crash out. Only if I go to the inbox from left drawer or top nav area - not from bottom nav.

**Steps to Reproduce**  
1. Go to 'left nav panel'
2. Click on 'inbox'
3. Use drop down to select any different view (for example 'all mentions')
4. See crash

**Expected behavior**  
A functional inbox like when using bottom nav button.

**Device information**

    Sync version: v23.09.13-18:19    
    Sync flavor: googlePlay    
    
    Ultra user: false    
    View type: List    
    
    Device: bluejay    
    Model: Google Pixel 6a    
    Android: 13

**Comment by momnom** [comment]
This is still happening, btw. More people have been mentioning it on the Lemmy community recently, too. Just a little update in case anyone else checks here with an inbox-crashes-Sync problem.

**Comment by momnom** [comment]
Lol, whoops

**Comment by momnom** [comment]
Should be fixed as of beta 109. Closed in anticipation of the release.

**Comment by laurencedawson** [comment]
Thanks for closing.
