### ISSUE TITLE
Changing app icon crashes app

### ISSUE THREAD

**Issue by icorbrey** [laurencedawson/sync-for-lemmy#45]
**Describe the bug**  
The app crashes when attempting to change the app icon.

**Steps to Reproduce**  
1. Go to Settings
2. Click on General
3. Scroll down to General
4. Click on Launcher Icon
5. Select Default

**Expected behavior**  
The app icon should have changed successfully.

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - Android: 13
 - Sync version: v23.07.24-19.51 (3)
 - Sync variant: S4L Beta 3

**Comment by corylowry12** [comment]
happens to me too

**Comment by laurencedawson** [comment]
Fixed for the next release!
