### ISSUE TITLE
Network Error notification spam

### ISSUE THREAD

**Issue by Mwj341** [laurencedawson/sync-for-lemmy#453]
**Describe the bug**  
While scrolling through my own profile's comment history, I was spammed with Network Error notifications.

**Steps to Reproduce**  
1. Go to profile
3. Scroll down 
4. Network error notifications will start spamming your device

**Screenshots**  
![Screenshot_20230930-145017](https://github.com/laurencedawson/sync-for-lemmy/assets/4852185/a8709467-9844-4aa1-a404-4df264cfff66)

https://discord.com/channels/684912692485554230/1120741766820286464/1157767973931593778 (video of bug in action. If you refresh and repeat steps, you'll get the same bug everytime. 

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - Android: 13
 - Sync version: v23.09.19-20: 43 (95)
 - Sync variant: I don't think this is relevant any more?

**Comment by laurencedawson** [comment]
Are you still getting this issue? I can't replicate it. Cheers.
