### ISSUE TITLE
Can't edit posts for community I mod

### ISSUE THREAD

**Issue by kringger** [laurencedawson/sync-for-lemmy#456]
**Describe the bug**  
Be a mod and post in your own community. Attempt to edit the post. Can't. 

**Steps to Reproduce**  
1. Be a mod
2. Post in your own community 
3. Click 3-dot
4. Edit option is not there

**Expected behavior**  
Edit option should be there 

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: pixel 6 pro
 - Android: 12
 - Sync version: latest
 - Sync variant: latest

**Additional context**  
If you try to edit a post in a community you are not a mod of, the option is there. Additionally, there is no way to edit titles of posts in the app.

**Comment by laurencedawson** [comment]
This has been fixed for the next release.
