### ISSUE TITLE
App crashes when trying to access the three-dot menu or sort menu (on Android 14)

### ISSUE THREAD

**Issue by ThoCor** [laurencedawson/sync-for-lemmy#458]
**Describe the bug**  
The app crashes immediately after I tap the three dots icon or the sort icon in the top right corner.
This bug began occuring after I've updated my Pixel to Android 14. Before that it worked fine. 

**Steps to Reproduce**  
1. Open the app.
2. Click on the three-dot menu button or the sort button.
3. The app crashes.

**Expected behavior**  
Not crash. :-)

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - Android: 14 stable release
 - Sync version: v23.09.13-18:19

**Comment by laurencedawson** [comment]
Are you still having this issue?

**Comment by CorvetteCole** [comment]
I had this issue, it was solved by disabling transparent navigation bar in developer settings

**Comment by ThoCor** [comment]
No, I don't. It's been there for months but then suddenly it was gone
about a week or two ago. Now seeing the comment by CorvetteCole I try to
remember if I changed any Android settings around that time but I don't
remember doing so. 

Am 06.03.2024 14:46 schrieb Laurence Dawson: 

> Are you still having this issue? 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/laurencedawson/sync-for-lemmy/issues/458#issuecomment-1980912914
[2]

**Comment by laurencedawson** [comment]
Added a fix for the next release.

**Comment by laurencedawson** [comment]
> I had this issue, it was solved by disabling transparent navigation bar in developer settings

Thanks for this! Helped fixed the issue.
