### ISSUE TITLE
App crashes following Beta 96 update if "Hide username in account picker" is enabled

### ISSUE THREAD

**Issue by GitWhatYouGive** [laurencedawson/sync-for-lemmy#460]
**Describe the bug**  

**Steps to Reproduce**  
1. Open app
2. Immediate crash
3. Delete cache and data and reconfigure all preferences
4. Enable "Hide username in account picker" 
5. App crashes again

**Additional context**  
As discovered in [this comment](https://sh.itjust.works/comment/6149644)

**Comment by EtzBetz** [comment]
I can confirm this, I updated my Sync to 96, then it only kept crashing. Funnily enough I was able to retain my settings by opening the link to the comment above, then navigating to the sub and the going into the setting and disabling hidden accounts.

**Comment by laurencedawson** [comment]
This has since been fixed.
