### ISSUE TITLE
"Show avatars" setting change not applying

### ISSUE THREAD

**Issue by GitWhatYouGive** [laurencedawson/sync-for-lemmy#461]
**Describe the bug**  
Disabling avatars in [Settings shortcut: Account settings > Show avatars](sync-settings://37-show_avatars) doesn't appear to save

**Steps to Reproduce**  
1. Go to [Settings shortcut: Account settings > Show avatars](sync-settings://37-show_avatars)
2. Disable avatars

**Expected behavior**  
Avatars should be disabled and hidden

**Comment by bertok** [comment]
To expand on this: it appears that saving does indeed work, as I can look through the settings menus and come back to this option to see it still properly set.

After opening a post or restarting the app this setting be reverted.
