### ISSUE TITLE
Occasional NSFW image in Everything

### ISSUE THREAD

**Issue by BoringHusband** [laurencedawson/sync-for-lemmy#462]
Since the 23:11:29 update there are occasional NSFW images in Everything even though the filters are all on.

Even though I all NSFW for my account I expect all the NSFW filters to work. The images I do see are marked NSFW and blurred, so at least the 'Blur preview' filter seems to be working.

I don't want provide a screenshot.

 - Device: Pixel 8
 - Android: 14
 - Sync version: v23.11.29
 - Sync variant: standard

**Comment by BoringHusband** [comment]
![Screenshot_20231202-121403](https://github.com/laurencedawson/sync-for-lemmy/assets/152695227/0d74f2a5-9fc3-487f-95a5-fe42dbf73c21)

**Comment by quick7silver** [comment]
I have the same issue and version of lemmy. All my NSFW settings are set to hide these posts and I've had to block a lot of communities but new ones keep popping up.

Happy to provide more info if anything specific is needed.

**Comment by laurencedawson** [comment]
Does this issue still persist? Unable to replicate my end. Cheers
