### ISSUE TITLE
Sync crashes when viewing this posts comments 

### ISSUE THREAD

**Issue by TurnItOff-OnAgain** [laurencedawson/sync-for-lemmy#464]
**Describe the bug**  
When opening this post while logged into Lemmy.world and trying to scroll or any anything in the comments sync crashes 

https://sopuli.xyz/post/6905885

**Steps to Reproduce**  
1. View everything feed
2. Open post
3. Attempt to scroll or collapse comment 
4. Crash

**Expected behavior**  
Should work as expected 

**Screenshots**  
https://files.catbox.moe/4d7e55.mp4

**Smartphone (please complete the following information):**
 - Device: galaxy s22
 - Android: 14
 - Sync version: 23.11.29 (96)

**Comment by stephen304** [comment]
I'm wondering if this is the same issue I'm having when viewing this posts comments: https://lemmy.world/post/9491179

Specifically, it crashes anytime I try to expand the 2 replies to this comment:
https://lemmy.ca/comment/5642080

Pixel 5
Lineage 20 Android 13
Sync version v23.11.29-22:27

**Comment by laurencedawson** [comment]
This was fixed in the latest update.
