### ISSUE TITLE
Random NSFW Button Loading Perpetually

### ISSUE THREAD

**Issue by ImpishCook** [laurencedawson/sync-for-lemmy#467]
**Describe the bug**  
Whenever I select the Random NSFW action bubble under the "More actions" banner at the top of the app, a loading screen appears towards the bottom third of my screen with a pinwheel that never pulls up the random NSFW community I requested. I've waited up to 5 minutes to see if the action request would be fulfilled with no response. 

**Steps to Reproduce**  
1. Uninstall Sync for Lemmy
2. Install Sync for Lemmy
3. Sign in to an account
4. Enable NSFW content in settings
5. Select the "More actions" banner via the ":" button at the top of the home splash screen for the app
6. Select the ":" button at the top right of the "More actions" banner
7. Select "Actions"
8. Toggle "Random NSFW" such that a check appears in its radio box
9. Press the "Random NSFW" action bubble under the "More actions" banner
10. Wait because the action is never fulfilled

**Expected behavior**  
I expect the above action to execute within a reasonable time frame of say 10-15 seconds, taking me to a random NSFW community on Lemmy. 

**Screenshots**  
![Screenshot_20231228_074528_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/155080431/f7b55ddc-dc3d-4698-a1bc-8614da5099f7)

![Screenshot_20231228_074550_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/155080431/956f8bf0-860a-4550-be08-5935ef4b09fa)

**Smartphone (please complete the following information):**
 - Device: Galaxy S23+
 - Android: 13
 - Sync version: v23.11.29-22:27
 - Sync variant: base

**Additional context**  
The action previously worked for me for a time, where it would execute as I expected it to and as I described above. At some point the action failed to execute, and I can speculate that the reason for this is that the random NSFW action cannot find any further communities that I haven't already seen. That's ok though. I would also expect the action to take me to communities I've already seen, and ones I haven't.

**Comment by laurencedawson** [comment]
This has since been fixed.
