### ISSUE TITLE
Redgifs videos are low quality, have no sound, and can't be downloaded

### ISSUE THREAD

**Issue by jimmyhiggs337** [laurencedawson/sync-for-lemmy#470]
**Describe the bug**  
When loading a redgifs video it loads the low rez soundless thumb version of a video rather than the video with sound.

When the download button is clicked, the download fails

**Steps to Reproduce**  
1. Go to home page or community
2. Click on a redgifs video
3. Video loads but their is no sound
4. Click the download button 
5. Receive notification saying "error saving media"

**Expected behavior**  
1. Go to home page or community
2. Click on a redgifs video
3. Video loads with the option to unmute sound
4. Click the download button 
5. Media is downloaded

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: Asus Zenfone 9
 - Android: 13
 - Sync version: v23.11.29-22:27
 - Sync variant: Beta, with sync ultra

**Additional context**  
it appears this is happening because Sync is pulling the api V2 URL rather than the api V3 URL and so the wrong version of the redgifs video is being served.

**Comment by momnom** [comment]
There's an issue that covers redgifs, it looks like:

https://github.com/laurencedawson/sync-for-lemmy/issues/339

Might be worth checking or adding info there?

**Comment by laurencedawson** [comment]
Thanks for closing!
