### ISSUE TITLE
Unable to edit post tile when editing post

### ISSUE THREAD

**Issue by jimmyhiggs337** [laurencedawson/sync-for-lemmy#471]
**Describe the bug**  
Unlike Reddit, lemmy allows you to edit post titles. When I edit a post, there is no option to edit a post title.

- Only text posts can be edited
- image posts can not be edited at all despite the fact that lemmy allows for images and titles to be changed after they are uploaded

**Steps to Reproduce**  
1. Go to my user profile
2. Click on posts
3. Scroll down to an image post
4. There is no edit button

1. Go to my user profile
2. Click on posts
3. Scroll down to a text post
4. Click the edit button
5. There is no option to edit post title

**Expected behavior**  
1. Go to my user profile
2. Click on posts
3. Scroll down to any post
4. Click the edit button
5. There is an option to edit image, title, body text etc.

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: Asus Zenfone 9
 - Android: 13
 - Sync version: v23.11.29-22:27
 - Sync variant: Beta, with sync ultra

**Comment by laurencedawson** [comment]
Added for the next release.
