### ISSUE TITLE
Combine Sync for Reddit and Sync for Lemmy into one app

### ISSUE THREAD

**Issue by candroid-man** [laurencedawson/sync-for-lemmy#473]
I know Sync for Reddit is no longer with us, but why can't it be? Infinity for Reddit is doing a $3 a month subscription for the cost of API usage, why can't Sync for Reddit do the same? Also people are able to bypass the API restrictions with ReVanced, or simply generate their own API key for the Reddit client.

And then, combining both apps would be really cool, so you can switch between your Reddit accounts and Lemmy accounts all you want!

**Comment by laurencedawson** [comment]
Sorry all work on S4R has ended.
