### ISSUE TITLE
RedGifs unable to load

### ISSUE THREAD

**Issue by tagelthebagel** [laurencedawson/sync-for-lemmy#474]
**Describe the bug**  
It seems like when searching for this Issue #58 and #24 seemed similar and stated they where fixed. But same issue with all redgifs not loading on the App. On an Android phone Samsung 10+

**Steps to Reproduce**  
Click on any RedGif and it will load "Could Not Load Video"

**Expected behavior**  
Gif should load 

**Screenshots**  
![Screenshot_20240301-085604_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/49094638/713ecb91-8b9b-4fa3-af88-349a2e966bc9)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy 10+
 - Android: 12
 - Sync version: 23.11.29-22:27
 - Sync variant: Unsure

**Additional context**

**Comment by candroid-man** [comment]
I am also experiencing this

**Comment by corylowry12** [comment]
This seems to be fixed now?

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
