### ISSUE TITLE
Wide spread crashing reported by all users

### ISSUE THREAD

**Issue by Sh4d** [laurencedawson/sync-for-lemmy#475]
**Describe the bug**  

Wide spread users are reporting crashes in the sync community. It may be triggered by multiple posts, since I still see it after blocking programmerhumor. 

[See this thread](https://midwest.social/post/9381826)  

Sounds like it's triggered by posts from https://neon.nightbulb.net/ as per https://lemmy.ca/comment/7738987

**Steps to Reproduce**  

Go to the report thread in the sync community and scroll down through the comments, sync will crash. It also happens in the feed. 

**Expected behavior**  
Don't crash.

**Comment by laurencedawson** [comment]
Fixed for the next release. Thanks for the report.
