### ISSUE TITLE
When swapping between automatic and manual theming, some elements don't change color properly 

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#479]
**Describe the bug**  

**Steps to Reproduce**  
1. Go to Settings
2. Click on Theme Management
3. Swap between manual and automatic 

**Expected behavior**  

- The UI element colors to be updated properly 

**Screenshots**  
![Screenshot_20240305-131247](https://github.com/laurencedawson/sync-for-lemmy/assets/8837361/25be50e8-1cd3-4d35-a309-5440bd16af88)
![Screenshot_20240305-131240](https://github.com/laurencedawson/sync-for-lemmy/assets/8837361/9d3a2c67-9606-429f-bf47-353eed2070ba)

**Smartphone (please complete the following information):**
 - Device: Pixel 8 Pro
 - Android: 14
 - Sync version: v24.03.05-18:44

**Comment by laurencedawson** [comment]
Were those elements off screen when changing theme?

**Comment by corylowry12** [comment]
This was fixed as of beta 109

**Comment by laurencedawson** [comment]
I thought so. Thanks for the update.
