### ISSUE TITLE
Capital letters are not allowed in username field

### ISSUE THREAD

**Issue by NomNuggetNom** [laurencedawson/sync-for-lemmy#5]
**Describe the bug**  
Capital letters can't be entered in the "Username" field on the login screen.

**Steps to Reproduce**  
1. Go to 'Add Account'
2. Click on the 'Username' field
3. Type a capital letter
4. The letter does not seem to appear in the field

**Expected behavior**  
Letter should go in the field

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - Android: 13
 - Sync version: v23.07.24-19:15 (5)
 - Sync variant: Lemmy

**Comment by brad-anderson** [comment]
The fix is probably the same, but pasting something with capital letters strips the capital letters from the pasted text, leaving just the lowercase letters.
