### ISSUE TITLE
Importing backup from Sync for Reddit set unusable comment sort

### ISSUE THREAD

**Issue by sethkinast** [laurencedawson/sync-for-lemmy#50]
**Steps to Reproduce**  
1. Import Sync for Reddit backup. See that it works great and sets all my theme options.
2. Realize that comments no longer load. Find out from LJ that you can long-press the error toast
3. See `Query deserialize error: unknown variant 6, expected one of Hot, Top, New, Old`
4. Realize that backup must have been sorting comments by "Best" or something.
5. Reset default comment sort, comments all load again

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android: 13

**Additional context**  
Backup was from Sync Pro about a month old.

**Comment by laurencedawson** [comment]
I've changed the name of this setting so this won't happen in future. Cheers.
