### ISSUE TITLE
Images not showing in some comments

### ISSUE THREAD

**Issue by gazelle8844** [laurencedawson/sync-for-lemmy#51]
**Describe the bug**  
Images not showing in comments when using Slides view and "Show image previews" toggled off in View Type Settings;
Comment Settings/Post Preview Media Size set to Full Height

(Also, some of the images show in post view, but others do not.)

**Steps to Reproduce**  
Go to these Examples of posts in Sync for Lemmy:

https://lemmy.world/post/1611193
  
https://lemmy.world/post/1568049

https://lemmy.ml/post/1915387

(Or just go to Earthporn@lemmy.ml to view the posts.) 

**Expected behavior**  
To be able to see image in the comments and click on it to view.

**Smartphone (please complete the following information):**
 - Device: Samsung A53 5G
 - Android: 13
 - Sync version: v23.07.25-00:38(7)
 - Sync variant: beta

**Additional context**

**Comment by laurencedawson** [comment]
What do you mean not showing sorry? Can you include a screenshot?

**Comment by gazelle8844** [comment]
Here is another example post:

https://lemmy.world/post/2143694  

First screenshot is post view, second is comments. There should be a cat picture in both screenshots. As I said in my first comment, I am using the Slides view with "Show image previews" turned off. (These are the same settings that I used in Sync for Reddit.) If I change my view from Slides to Small Cards, I am able to see the images.  

![Screenshot_20230725_140848_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/102678194/92347282-e08a-4cad-b60c-bd369980b9d7)

![Screenshot_20230725_140933_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/102678194/a81408d6-629a-47ca-9672-131c37990b08)
