### ISSUE TITLE
Not showing link options properly and crashing when clicked

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#513]

**Comment by corylowry12** [comment]
![Screenshot_20240318-000427](https://github.com/laurencedawson/sync-for-lemmy/assets/8837361/f41ece1d-ab12-4943-a96a-c6929e6ee3d6)

**Comment by corylowry12** [comment]
https://lemmy.world/post/13248612

**Comment by corylowry12** [comment]
In that test post sync is also inserting the spoiler tags wrong and the lemmy website is not parsing it due to it not being the proper ::: for spoilers

**Comment by laurencedawson** [comment]
Fixed!
