### ISSUE TITLE
Clicking on user names redirects to Reddit

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#52]
**Describe the bug**  

**Steps to Reproduce**  
1. Go to any post
2. Click on the post to open the comments
3. Scroll down to the comments
4. Click on the username with "Tap usernames to open" enabled in "Link Handling"
5. Notice the app opens a custom tab that redirects to Reddit

**Expected behavior**  
Open the view of the lemmy user

**Smartphone (please complete the following information):**
 - Device: S22 Ultra
 - Android: 13
 - Sync version: 23.07.25-00:55

**Comment by laurencedawson** [comment]
Fixed
