### ISSUE TITLE
Some images don't load

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#54]
**Describe the bug**  

**Steps to Reproduce**  
1. Go to a post in the main feed
2. Notice on some of them it's just a gray box
3. Click on image to verify it'll load
4. Go back and see that image isn't showing
5. Sometimes it'll show and then readjust the size of the view accordingly after going back
6. If image still doesn't load, long pressing on the image displays "Glide failed to load this image"

**Expected behavior**  
- The image to load

**Smartphone (please complete the following information):**
 - Device: S22 Ultra, Pixel Tablet
 - Android: 13
 - Sync version: v23.07.25-01:05

**Comment by laurencedawson** [comment]
I've set a timeout in beta 10 (#46) closing this for now but let me know if you see it again and raise another ticket. Cheers.
