### ISSUE TITLE
Can't click on communities

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#55]
**Describe the bug**  

**Steps to Reproduce**  
1. Go to the main feed
2. Click on the community name
3. Toast message is shown stating unable to open r/communityname

**Expected behavior**  
A clear and concise description of what you expected to happen

- it to open

**Screenshots**  

![Screenshot_20230724_194651_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/8837361/ffb30941-968d-4068-8a51-3272a8726bd3)

**Smartphone (please complete the following information):**
 - Device: S22 ultra 
 - Android: 13
 - Sync version: v23.07.25-01:05

**Comment by laurencedawson** [comment]
Fixed!
