### ISSUE TITLE
App still parses subreddits

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#56]
**Describe the bug**  

**Steps to Reproduce**  
1. Go to a post
2. Scroll down to a comment that has r/community in it 
3. The r/community is a hyperlink 
4. Get a toast error when clicking on it

**Expected behavior**  

- not to be a link

**Screenshots**  

![Screenshot_20230724_200606_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/8837361/9f3caa33-f21a-4859-8749-1bd91772ba26)

**Smartphone (please complete the following information):**
 - Device: S22 ultra
 - Android: 13
 - Sync version: v23.07.25-01:05

**Comment by laurencedawson** [comment]
Fixed.
