### ISSUE TITLE
Fast scrolling option and community sort is non-alphabetical 

### ISSUE THREAD

**Issue by kringger** [laurencedawson/sync-for-lemmy#57]
**Describe the bug**  
Fast scrolling option in Explore and the community sort is non-alphabetical 

**Steps to Reproduce**  
1. Go to 'Explore'
2. Enable "Fast Scrolling"
3. See non-alphabetical sort on the right 

**Expected behavior**  
This should be alphabetical.

**Screenshots**  

![Screenshot_20230724-211150.png](https://github.com/laurencedawson/sync-for-lemmy/assets/35173157/f4db34a3-189f-4484-9fdf-888a499560ce)

**Smartphone (please complete the following information):**
 - Device: Pixel 6 pro
 - Android: 13
 - Sync version: Beta 9
 - Sync variant: Beta 9

**Additional context**  
None

**Comment by laurencedawson** [comment]
The biggest question here is how on earth are your communities out of order...

**Comment by kringger** [comment]
How can I provide further details to assist?

**Comment by kringger** [comment]
I think a few things are going on here. 

Firstly, in my original screenshot above you can see that the top 3 communities in the list are listed as community@null (which I believe is a separate bug related to kbin.social communities. 

![Screenshot_20230725-123422.png](https://github.com/laurencedawson/sync-for-lemmy/assets/35173157/a96b6da8-f53a-4c0a-9c36-de3ceaf82c45)

![Screenshot_20230725-123434.png](https://github.com/laurencedawson/sync-for-lemmy/assets/35173157/c542a99e-ac24-4d0f-bb20-641d2fcc81b4)

![Screenshot_20230725-123446.png](https://github.com/laurencedawson/sync-for-lemmy/assets/35173157/b533b308-4c0c-4880-9536-e64290d152b6)

Secondly, I believe the "fast scrolling" option is pulling the first letter of the display name instead of the community slug. You can see this here:

![Screenshot_20230725-123643.png](https://github.com/laurencedawson/sync-for-lemmy/assets/35173157/3c07ea2d-8398-43f4-bc27-1698b75b2cc3)

The display name is "The Reddit Archive" but when actual slug is "archive@lemmy.world"

**Comment by kringger** [comment]
@laurencedawson I think this is definitely the reason. The reason I'm getting the ? for the letter N is because they have an emoji in the display name.

![Screenshot_20230725-145935.png](https://github.com/laurencedawson/sync-for-lemmy/assets/35173157/c5db64a2-032b-4790-bffa-8b14cd0876aa)

I think you should sort by display name, and then below where you have the instance name, you could put the full !community@instance.tld

Maybe an option/toggle to prefer display names or prefer community names.

**Comment by kringger** [comment]
@laurencedawson So this is somewhat fixed in beta 14, but I think we need to have the full community slug visible underneath so that it is apparent to users why a community with the display name "The Reddit Archive" is alphabetized by "A" (the community is archive@lemmy.world).

Additionally, the kbin@null communities still mess up the order of some letters. I know that is being worked on in a different issue.

Lastly, I see a minor graphical bug with using fast scrolling:

Opening the explore tab looks like this initially (which is great)

![Screenshot_20230726-212048.png](https://github.com/laurencedawson/sync-for-lemmy/assets/35173157/30e12164-1506-489f-8c20-b46a3c1df831)

But when you expand the sheet to fullscreen the expansion arrows in the right shift inward.

![Screenshot_20230726-212051_1.png](https://github.com/laurencedawson/sync-for-lemmy/assets/35173157/5cf2e4b0-95fc-4771-b6ce-7ac57869b7f4)

Expanding any section other than "subscriptions" keeps this expanded area blank

![Screenshot_20230726-212055_1.png](https://github.com/laurencedawson/sync-for-lemmy/assets/35173157/f29e3045-b89e-425c-a722-79a4b7fb8b58)

And only when you expand the "subscription" category does the fast scrolling alphabet appear (with letters still messed up presumably due to kbin@null)

![Screenshot_20230726-212059.png](https://github.com/laurencedawson/sync-for-lemmy/assets/35173157/4ca9f66a-44c2-42ac-a263-0a3496ef6635)
