### ISSUE TITLE
selftext previews not displaying correctly

### ISSUE THREAD

**Issue by Phuntis** [laurencedawson/sync-for-lemmy#59]
selftext previews are displaying formatting characters rather than using them to format so for example in these screenshots in the full post it says "**X**" but in the preview it says "#X"

![Screenshot_20230725-024543.png](https://github.com/laurencedawson/sync-for-lemmy/assets/78653137/25a06791-91ca-41c6-b06e-c96e81656e0c)

![Screenshot_20230725-024539.png](https://github.com/laurencedawson/sync-for-lemmy/assets/78653137/65384b3b-47bd-4f27-bbe2-6b77b3e9cf9d)

**Comment by laurencedawson** [comment]
Not a bug I'm afraid, working the same as S4R for now.
