### ISSUE TITLE
Kebab Menu causes DeadObjectException

### ISSUE THREAD

**Issue by GittyMac** [laurencedawson/sync-for-lemmy#6]
**Describe the bug**  
Clicking the kebab menu on the Posts screen causes a DeadObjectException, which crashes the app. 
EDIT - This only seems to crash when the 'Transparent navigation bar' developer flag is enabled.

**Steps to Reproduce**  
1. On the Posts page, click the Kebab Menu.

**Expected behavior**  
A menu should open.

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - Android: 14 Beta 4
 - Sync version: v23.07.24-19:51
 - Sync variant: Internal

**Additional context**  
`Exception thrown during dispatchAppVisibility Window{953b12b u0 io.syncapps.lemmy_sync/io.syncapps.lemmy_sync.ui.activities.MainActivity EXITING}`

**Comment by GittyMac** [comment]
It appears the issue also affects the sort menu.

**Comment by GittyMac** [comment]
> Could this be an Android 14 issue you think?
> 
> I'm seeing the issue come through on Crashlytics and it seems to be the Material Design library crashing.

I found out it only crashes when the Developer Options toggle 'Transparent navigation bar' (Introduced in Android 14) is enabled and when a sheet opens from the top.

**Comment by laurencedawson** [comment]
Ah gotcha. I'll keep this open and try updating the material design lib now.

**Comment by laurencedawson** [comment]
Beta 7 is live with this fix, let me know if it helps. Cheers

**Comment by GittyMac** [comment]
It still crashes on Beta 9

**Comment by th0mcat** [comment]
> > Could this be an Android 14 issue you think?
> > I'm seeing the issue come through on Crashlytics and it seems to be the Material Design library crashing.
> 
> I found out it only crashes when the Developer Options toggle 'Transparent navigation bar' (Introduced in Android 14) is enabled and when a sheet opens from the top.

Can confirm disabling "Force transparent nav bar" fixes the issue.

**Comment by laurencedawson** [comment]
Looks like the last Android 14 beta fixes this. Can anyone confirm?

**Comment by GittyMac** [comment]
Still crashes on Beta 5.2 (UPB5.230623.006)

**Comment by laurencedawson** [comment]
I updated the material library for beta 50, can anyone confirm if this fixes the issue?

**Comment by GittyMac** [comment]
Still crashes on 23.08.31-21:16

**Comment by laurencedawson** [comment]
I'm still seeing this come through on Crashlytics. Keeping an eye out for any updates from Google.

**Comment by laurencedawson** [comment]
Fixed for the next release.
