### ISSUE TITLE
Hide action does not work

### ISSUE THREAD

**Issue by Ictinus** [laurencedawson/sync-for-lemmy#60]
**Describe the bug**  
The action to hide a post does not work. After refresh, the post reappears.

**Steps to Reproduce**  
1. Go to 'Everything'
2. Click on a 'Post Options -> Hide', see the post disappear.
3. Click on top of page 'More actions -> Refesh'
4. Scroll down to find the requested post return.

**Expected behavior**  
After successfully hiding a post and refreshing the list of posts, the post in question should not reappear.

**Smartphone (please complete the following information):**
 - Device:  Pixel 6
 - Android: 13
 - Sync version: e.g. v23.07.25-01:05
 - Sync variant: Beta 9

**Comment by laurencedawson** [comment]
Currently Lemmy doesnt support hide so it's only hiding locally.

Not quite sure how to handle this one.

**Comment by beerbaronstatic** [comment]
Would a temporary solution be to use https://join-lemmy.org/api/interfaces/MarkPostAsRead.html? Unfortunately that still relies on the user having their actual Lemmy account settings to have "show read" unchecked

**Comment by Ictinus** [comment]
If the API for hiding isn't yet supported, perhaps https://developers.google.com/drive/api/guides/appdata

**Comment by Joristdh** [comment]
Wouldn't it be possible to utilize the existing local post filter mechanism to persist hidden posts across refreshes?

**Comment by waldyrious** [comment]
Update: the issue in the lemmy repository has been reopened! :tada: Hopefully it will soon be available for Sync and other apps to make use of.

**Comment by laurencedawson** [comment]
For now hidden posts will remain hidden in Sync as of beta 30.

**Comment by waldyrious** [comment]
@laurencedawson for a while now I've noticed that posts no longer seem to remain hidden in Sync, so I suspect the approach mentioned above doen't work anymore, or has some sort of cache issue.

That said, I came here to share that the [upstream issue](https://github.com/LemmyNet/lemmy/issues/1403) has finally been resolved with https://github.com/LemmyNet/lemmy/pull/4480, so you may want to look into that functionality to base Sync's implementation upon.
