### ISSUE TITLE
Add support for exclamation links

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#63]
**Describe the bug**  
In the web interface and in Jerboa, exclamation links are automatically parsed

**Steps to Reproduce**  
1. Go to https://lemmy.zip/post/720895
2. Look at post 
3. 
4. 

**Expected behavior**  
The exclamation link should be parsed. 

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: [e.g. v22.5.20]
 - Sync variant: [e.g. pro]

**Additional context**

**Comment by laurencedawson** [comment]
Added.
