### ISSUE TITLE
Pressing messaging in settings causes crash

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#64]
**Describe the bug**  
Pressing Messaging in settings causes a crash

**Steps to Reproduce**  
1. Go to app settings
2. Click on messaging
3. Crash 
4. Cry 

**Expected behavior**  
The section should open

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: [e.g. v22.5.20]
 - Sync variant: [e.g. pro]

**Additional context**

**Comment by laurencedawson** [comment]
Fixed.
