### ISSUE TITLE
Settings -> Link handling -> how do I set chrome flags fails to load

### ISSUE THREAD

**Issue by Coffee-Viking** [laurencedawson/sync-for-lemmy#66]
**Describe the bug**  
Settings -> Link handling -> how do I set chrome flags shows the "loading/reload" icon but nothing happens

**Steps to Reproduce**  
1. Go to settings
2. Click on link handling
3. Scroll down to how do I set custom Chrome flags

**Expected behavior**  
An explanation should open

**Screenshots**  
https://imgur.com/a/J4684Rk

**Smartphone (please complete the following information):**
 - Device: One plus 10 pro
 - Android: 12
 - Sync version: 23.07.25-1:05
 - Sync variant: alpha

**Additional context**  
I don't have Chrome installed on my phone, only Chrome Beta (in case that makes a difference for link handling). My default browser however is Fennec (Firefox variant).

**Comment by kontrastylez** [comment]
Same behavior with standard Chrome installed on

Device: Pixel 6a and Pixel Tablet
Android: 13
Sync version: 23.07.25-01:05 (9)

**Comment by laurencedawson** [comment]
Added.
