### ISSUE TITLE
Sync incorrectly identifies the OP

### ISSUE THREAD

**Issue by mikeyd85** [laurencedawson/sync-for-lemmy#67]
**Describe the bug**  
Sync incorrectly identifies the OP when a user has the same user name but is from a different instance. 

**Steps to Reproduce**  
1. Create a post with a user from one instance 
2. Login as a user from a different instance with the same name
3. Sync identifies different instance user as OP

**Expected behavior**  
User not indetified as OP. 

**Smartphone (please complete the following information):**
 - Device: S21 Ultra

**Comment by mikeyd85** [comment]
![Screenshot_20230725_074211_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/64745331/f99480b4-7b54-4ad8-b075-9fad4b75253d)

**Comment by laurencedawson** [comment]
Fixed for the next release.
