### ISSUE TITLE
Saving comment as a draft doesn't work

### ISSUE THREAD

**Issue by kv1dr** [laurencedawson/sync-for-lemmy#68]
**Describe the bug**  
Replying to a post always shows empty EditText even if we previously saved comment as a draft.

**Steps to Reproduce**  
1. Go to any post
2. Click on Reply
3. Type anything in comment section
4. Press back button
5. App asks you if you want to Discard? Choose Save draft
6. Click on Reply again
7. Comment section is empty

**Expected behavior**  
Comment section should be filled with last saved draft.

**Screenshots**  
![Sync1_](https://github.com/laurencedawson/sync-for-lemmy/assets/851420/86567eec-e528-4429-9e00-0383a03f8c13)
![Sync2_](https://github.com/laurencedawson/sync-for-lemmy/assets/851420/ca8ef080-ed71-4100-ac4c-0cf951530110)
![Sync3_](https://github.com/laurencedawson/sync-for-lemmy/assets/851420/1c151494-b3cd-41e7-8e71-8451503d0da4)
![Sync4_](https://github.com/laurencedawson/sync-for-lemmy/assets/851420/89d806eb-13f5-4375-ace3-d88a77f9a15b)

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - Android: 13
 - Sync version: v23.07.25-01:05
 - Sync variant: Free

**Additional context**  
Nothing

**Comment by Coffee-Viking** [comment]
The feature works, it's identical to S4R. To load the draft you need to click on the folder icon (third from the left in your last screenshot, after the eye and smiley icon) and then select the draft from the popup window.

All drafts you ever saved are there unless you delete them, it's not saved within the exact context but rather in a separate file on your phone.

**Comment by kv1dr** [comment]
Oh, I didn't know that. I just tried this and it works. Thanks. I will close this issue now.
