### ISSUE TITLE
Login screen does not prompt password managers

### ISSUE THREAD

**Issue by NomNuggetNom** [laurencedawson/sync-for-lemmy#7]
**Describe the bug**  
When on the login screen, password managers don't seem to be given the necessary hints to suggest logins.

**Steps to Reproduce**  
1. Go to 'Add Account'
2. Click on the 'Username' field
3. No password manager prompt

**Expected behavior**  
Password managers should suggest logins

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - Android: 13
 - Sync version: v23.07.24-19:15 (5)
 - Sync variant: Lemmy

**Additional context**  
Confirmed with both BitWarden and 1Password

**Comment by jpjonte** [comment]
Can confirm. But long pressing the username field and selecting autofill from the popup worked for me.

**Comment by laurencedawson** [comment]
Added additional hints to the input fields. Seems to play nicely with BitWarden now.
