### ISSUE TITLE
S4L doesn't pull/ignores web settings

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#70]
Sync should pull and respect web settings where possible.

**Comment by laurencedawson** [comment]
Any examples?

**Comment by pwd-github** [comment]
literally all these
![Screenshot_20230725-121654](https://github.com/laurencedawson/sync-for-lemmy/assets/203217/799c03f1-4608-42bf-bbb2-9088cec07980)

I had to turn on post avatars, post scores and NSFW manually in app

**Comment by laurencedawson** [comment]
Those dictate what is shown in the API. Sync doesn't control those settings.

e.g. disabling show read posts removes them from the API completely.

Is this ticket asking for these options to be made available in app?

**Comment by pwd-github** [comment]
in the Sync settings, there's filters, advanced, hide NSFW. That should ideally pull straight from the show NSFW content in the above screenshot? 

Am I making sense? I feel like I'm explaining poorly

**Comment by kringger** [comment]
I think he's saying sync should read and pull these prefs from the web to the app prefs?

I also think someone could think sync is not working properly if they have something like nsfw disabled on the web prefs but enabled in the app prefs. Maybe a link or tool tip to explain this would be good.

**Comment by pwd-github** [comment]
Yep

**Comment by pwd-github** [comment]
Think this is largely fixed, as per beta 20

**Comment by samuelspiza** [comment]
Any reason the Type (Subscribed / Local / All) setting is not a ticket? I like to view things Subscribed + New. But when you switch between accounts/instaces in S4L it always defaults to All + Active. I think Active/New is the sort setting ticket 163. But I don't see one for the type (Subscried/All) setting.

**Comment by pwd-github** [comment]
> Any reason the Type (Subscribed / Local / All) setting is not a ticket? I like to view things Subscribed + New. But when you switch between accounts/instaces in S4L it always defaults to All + Active. I think Active/New is the sort setting ticket 163. But I don't see one for the type (Subscried/All) setting.

#163 covers what you're referring to. The way lemmy is designed, it's one setting for all three

**Comment by laurencedawson** [comment]
All sorted! Big thanks for managing this issue.
