### ISSUE TITLE
cross-post option missing from posts

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#72]
**Describe the bug**  
Lemmy has a built-in option to cross-post, it's missing. 

**Steps to Reproduce**  
1. Go to a post
2. Click on the three dots 
3. Look around 
4. Find money down the back of the sofa 

**Expected behavior**  
Cross-post should be available

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: [e.g. v22.5.20]
 - Sync variant: [e.g. pro]

**Additional context**

**Comment by laurencedawson** [comment]
Submit isn't available yet. Merging with prior issue:

https://github.com/laurencedawson/sync-for-lemmy/issues/37
