### ISSUE TITLE
Stopping Read aloud on a comment isn't obvious

### ISSUE THREAD

**Issue by Ictinus** [laurencedawson/sync-for-lemmy#73]
**Describe the bug**  
Choosing 'Read aloud' from comment options does read the comment aloud, but then continues to read aloud all comments. There is no way to stop it other than to remove focus from comments... leave comments, minimise the app or close it.

**Steps to Reproduce**  
1. Go to a comment of post.
2. Click on comment options -> Read aloud
3. Hear that the comment is read followed by other comments.
4. Be confused as to how to stop it.

**Expected behavior**  
An obvious method should be shown to turn off Read aloud. Initially I expect it to only read the single comment, but perhaps having an on screen button (second fab?) appear to allow it to be turned off is better. 

The comment option could be better named 'Read aloud comments' perhaps.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - Android: 13
 - Sync version: v23.07.25-01:05
 - Sync variant: beta 9

**Comment by laurencedawson** [comment]
Did it not show the bar at the bottom?

**Comment by Ictinus** [comment]
sorry LJ, I must be blind. I certainly see it now.
