### ISSUE TITLE
Crash: Long-press action button crashes app

### ISSUE THREAD

**Issue by Coffee-Viking** [laurencedawson/sync-for-lemmy#74]
**Describe the bug**  
When long pressing the "actions" button in the bottom navigation bar, the app crashes.

**Steps to Reproduce**  
1. Go to settings, enable bottom navigation
2. Go to experimental settings, enable show actions
3. Go to frontpage, long-press actions in bottom navigation bar
4. Kaboom

**Expected behavior**  
No idea what the long press is supposed to do, probably just switch it off?

**Smartphone (please complete the following information):**
 - Device: OnePlus 10 Pro
 - Android: 12
 - Sync version: 23.07.25-1:05
 - Sync variant: beta 9

**Additional context**  
Long pressing "inbox" in the bottom bar opens the "send message" dialogue which is supposedly not yet implemented, where the button to include the link to Sync still points to the reddit app. Since the messaging feature is not yet implemented I'm not opening a separate ticket for this.

**Comment by laurencedawson** [comment]
@Coffee-Viking what was the first item in your actions menu? It's supposed to click that

**Comment by laurencedawson** [comment]
OK I can reproduce when its submit as the first item. Fixed.
