### ISSUE TITLE
Instance name is getting cut off in the sliding panel drawer

### ISSUE THREAD

**Issue by gazelle8844** [laurencedawson/sync-for-lemmy#75]
**Describe the bug**  
The instance name is getting cut off in the left sliding panel drawer

**Steps to Reproduce**  
1. Change your font size to a larger size
2. Open left side sliding panel drawer
3. At the very top, where it has username and instance name, the bottom part of the instance name is getting cut off

*Edit: I tried changing my font size to the smallest size available, and it did not change the instance name from getting cut off, so I honestly don't know how to reproduce this problem. (Also, on my second phone, which is a Motorola G Power running Android 11, I am not having this problem, the instance name is not getting cut off.)

**Expected behavior**  
To see the full username and instance name

**Screenshots**  
![Screenshot_20230725_052701_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/102678194/a608af52-c60e-467c-8fe7-9f94c103bd93)

**Smartphone (please complete the following information):**
 - Device: Samsung A53 5G
 - Android: 13
 - Sync version: v23.07.25-1:05(9)
 - Sync variant: beta

**Additional context**  
Also, I have several different accounts on different instances with all the same usernames and profile pictures. In the sliding panel drawer where it shows all of my profiles, all I can see is my username..., not the instance name, as it is also getting cut off there as well. So when I want to switch to a different instance, I cannot tell the difference between them since I am unable to see the instance name. This probably has something to do with the fact that I have a long username, and that I am using a larger font size. This problem occurs on both my phones, Samsung A53 5G running Android 13, and Moto G Power running Android 11.

**Comment by gazelle8844** [comment]
Edit 7/29/23- I turned off the setting "Sliding panel style drawer" in the Experimental part of the settings and now the instance name is no longer getting cut off in the side drawer at the top of the screen. (See screenshots)   
I am still having the issues that I listed above in the Additional Context"

![Screenshot_20230729_052916_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/102678194/8ec7b3ab-5917-4ca3-b379-b692ecbcbbe1)  

![Screenshot_20230729_053033_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/102678194/139769c1-adca-4707-a412-f602053134e0)

**Comment by laurencedawson** [comment]
Fixed
