### ISSUE TITLE
Support for verified links (top X instances maybe)

### ISSUE THREAD

**Issue by alcatrazblaze** [laurencedawson/sync-for-lemmy#77]
**Is your feature request related to a problem? Please describe.**  
No verified links currently

**Describe the solution you'd like**  
Adding verified links for top 10/15 instances

![Screenshot_20230725-162929_Settings.png](https://github.com/laurencedawson/sync-for-lemmy/assets/55349349/b0e41fc8-db44-4e1f-8e20-d9b27e2e642c)

**Comment by pwd-github** [comment]
Jerboa pills the top 55 instances I believe

**Comment by OvermindDL1** [comment]
In addition to a list of top instances by default, it would be nice to be able to customize it to put in our own links (like our own instance).

**Comment by laurencedawson** [comment]
This has since been added.
