### ISSUE TITLE
Dual pain landscape/portrait mode only displays one column.

### ISSUE THREAD

**Issue by Vlixz** [laurencedawson/sync-for-lemmy#79]
**Describe the bug**  
Enabling dual pane landscape/portrait mode on a tablet only displays one column.

**Steps to Reproduce**  
1. Enable dual pane landscape/portrait mode.
2. Go to home.
3. Only left pane is shown.

**Expected behavior**  
Both columns are displayed

**Screenshots**  
![Screenshot_2023-07-25-13-19-25-143_io.syncapps.lemmy_sync.jpg](https://github.com/laurencedawson/sync-for-lemmy/assets/71019504/a810c515-1b40-4606-8841-593eeb2b1abd)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Pad 5
 - Android: Android 13
 - Sync version: v23.07.25-01:05
 - Sync variant: Lemmy

**Comment by laurencedawson** [comment]
Nota bug. Click on any post to open the comments.

**Comment by Vlixz** [comment]
My bad, completely misunderstood the setting! Apologies
