### ISSUE TITLE
FABs are too big

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#81]
**Describe the bug**  

**Steps to Reproduce**  
1. Click on the explore tab
2. Scroll down until FAB is shown
3. See that FAB is too big

Judging from my experience, Google updated the material library and broke how the FAB size is normally set, it just doesn't work. I found you have to use style="?attr/floatingActionButtonSmallStyle" to actually get a mini FAB now

**Expected behavior**  

- The FAB to be a mini FAB

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: [e.g. v22.5.20]
 - Sync variant: [e.g. pro]

**Comment by laurencedawson** [comment]
Agreed. Fixed for the next release.

**Comment by corylowry12** [comment]
![Screenshot_20230725_075507_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/8837361/0d4046bb-7004-43cd-8401-500adbeb7382)
After the update the corner radius is off.
