### ISSUE TITLE
Subscribed feed fails to load

### ISSUE THREAD

**Issue by garpunkal** [laurencedawson/sync-for-lemmy#82]
Subscribed fails to load if a child community is failing to load:

![Screenshot_20230725-131027.png](https://github.com/laurencedawson/sync-for-lemmy/assets/13114807/788a1c1b-6a98-468a-9df5-ebaccc02fa6e)

Local feed looks ok:

![Screenshot_20230725-131049.png](https://github.com/laurencedawson/sync-for-lemmy/assets/13114807/964427d8-41ce-42ef-bc4f-21acd6011556)

Communities that are failing to load:

![Screenshot_20230725-131409.png](https://github.com/laurencedawson/sync-for-lemmy/assets/13114807/375d3cfc-d69e-40a5-934d-9474d47c023a)

**Comment by laurencedawson** [comment]
Fixed. Cheers.
