### ISSUE TITLE
App icon resizing when going home on one UI 

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#83]
**Describe the bug**  

**Steps to Reproduce**  
1. Open the app
2. Swipe to go home
3. The app icon size changes about half a second after you go home

**Expected behavior**  

- the app icon to be the same size

**Smartphone (please complete the following information):**
 - Device: S22 ultra 
 - Android: 13
 - Sync version: v23.07.25-01:05

**Comment by laurencedawson** [comment]
Can you take a video? Thanks

**Comment by corylowry12** [comment]
https://discord.com/channels/684912692485554230/1120741766820286464/1133372623728951346

**Comment by corylowry12** [comment]
This has been fixed in the one UI 6 beta
