### ISSUE TITLE
Fab corner radius is wrong

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#86]
**Describe the bug**  

**Steps to Reproduce**  
1. Go to explore tab
2. Scroll down 
3. See the fab has too high of a corner radius

**Expected behavior**  

The corner radius to be the same as before even though it's a smaller size

**Screenshots**  

![Screenshot_20230725_075507_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/8837361/ffe16724-6b9d-43dc-83b7-4971aa37d1a8)

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: [e.g. v22.5.20]
 - Sync variant: [e.g. pro]

**Additional context**

**Comment by laurencedawson** [comment]
Looks right to me:

https://m3.material.io/components/floating-action-button/specs

Checking the source its not a user configurable option either. This is hardcoded:

```
 @Override
    public float getRadius() {
      return getSizeDimension() / 2f;
    }
```
