### ISSUE TITLE
Reddit preferences menu option still present

### ISSUE THREAD

**Issue by garpunkal** [laurencedawson/sync-for-lemmy#9]
Clicking settings still shows Reddit preferences in settings menu

**Comment by jpjonte** [comment]
![Screenshot_20230724-231441](https://github.com/laurencedawson/sync-for-lemmy/assets/1562929/2e81a349-4322-4368-af0c-4ae2f0751167)
![Screenshot_20230724-231630](https://github.com/laurencedawson/sync-for-lemmy/assets/1562929/4afda3ac-b952-4b65-8248-0f988953a43b)

Messaging and Security settings also mention reddit.
