### ISSUE TITLE
kbin communities don't display instance address

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#90]
**Describe the bug**  
KBin communities either display null or are null where lemmy communities display the instance address. 

**Steps to Reproduce**  
1. Find a kbin community
2. Click on subscribe 
3. Check your subscriptions list
4. See missing instance address

**Expected behavior**  
You should see the instance address 

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - Android: 13
 - Sync version: beta 10
 - Sync variant: beta 

**Additional context**

**Comment by laurencedawson** [comment]
Fixed
