### ISSUE TITLE
Images fail to upload

### ISSUE THREAD

**Issue by Mwj341** [laurencedawson/sync-for-lemmy#91]
**Describe the bug**  
Uploading a picture from your device fails

**Steps to Reproduce**  
1. Go to comments and start a reply
2. Click on image uplpader icon, select from this device
3. Scroll down to image and hit upload
4. Get toast message saying upload failed

**Expected behavior**  
Upload image from my device and embed it in comment reply

**Screenshots**  
![Screenshot_20230725-081228](https://github.com/laurencedawson/sync-for-lemmy/assets/4852185/c9c36531-d5f1-41f1-9875-487cc891a1be)

**Smartphone (please complete the following information):**
 - Device: pixel 7 pro
 - Android: 13
 - Sync version: v23.07.25-13:31
 - Sync variant: S4L preview

**Additional context**

**Comment by kringger** [comment]
Same here.

Pixel 6 pro
Android 13
S4L Beta 12

![Screenshot_20230725-151041.png](https://github.com/laurencedawson/sync-for-lemmy/assets/35173157/26d31930-f5b6-4f38-ab27-8941ac81bb9e)

**Comment by kringger** [comment]
Maybe I can add my Gboard gif insertion request here as well Instead of making a new issue?

I'm not sure if Lemmy even supports inline gifs, as I've tried to insert them from Gboard on jerboa and via the webui to no avail. The one thing I've seen that comes close is a custom emoji gif, but idk how that works tbh. I just saw it once in a post

**Comment by kringger** [comment]
Furthermore, after selecting an image or gif, you could have an optional dialog box for the alt text (text that would go between the brackets). 

It was mentioned in the discord that people with visual impairments can benefit from alt text, so having this as an option is an accessibility feature.
