### ISSUE TITLE
Settings > View type is empty

### ISSUE THREAD

**Issue by kontrastylez** [laurencedawson/sync-for-lemmy#92]
**Describe the bug**  
The screen in Settings > View type is empty. When scrolling in this window, the app crashes.

**Steps to Reproduce**  
1. Go to 'Settings'
2. Click on 'View type'
3. Optional: Scroll up/down

**Expected behavior**  
Display view type settings and not crashing.

**Screenshots**  
![Screenshot_20230725-153509](https://github.com/laurencedawson/sync-for-lemmy/assets/23293407/4780e026-6540-47bb-9302-e6e923f16042)

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - Android: 13
 - Sync version: 23.07.25-13:31 (10)

**Comment by laurencedawson** [comment]
Fixed for the next release.

**Comment by corylowry12** [comment]
Also not fixed for me
