### ISSUE TITLE
Broken comment hierarchy in comments under View more

### ISSUE THREAD

**Issue by sanjilshah** [laurencedawson/sync-for-lemmy#93]
**Describe the bug**  
Child comments show up before the parent in the tree structure. Shows up in the same way after changing sort too.

**Steps to Reproduce**  
1. Open any post with lots of comments (>100 comments)
2. Click view more on any comment tree with a few comments
3. Child comments show up before the parent ones

Example:
https://lemmy.world/post/1698400

**Expected behavior**  
Tree structure with child comments nested under the parent

**Screenshots**  
![Screenshot_20230725-060303~2.png](https://github.com/laurencedawson/sync-for-lemmy/assets/46300822/e9250212-7619-478d-aee5-2c46fdfa2672)

**Smartphone (please complete the following information):**
 - Device: Motorola Edge 30 Ultra
 - Android: 12
 - Sync version: Beta 10
 - Sync variant:

**Comment by sanjilshah** [comment]
Beta13: View more on any comment thread stopped working. It just displays a toast "No comments added" and the button disappears without loading any nested comments

**Comment by laurencedawson** [comment]
Fixed!
