### ISSUE TITLE
Catbox.moe files don't embed 

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#99]
**Describe the bug**  
Images hosted on files.catbox.moe don't load 

**Steps to Reproduce**  
1. Go to https://lemmyf.uk/post/172521
2. The embedded image doesn't lose

**Expected behavior**  
Embedded image should load 

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - Android: 13
 - Sync version: beta 12
 - Sync variant: internal

**Additional context**

**Comment by laurencedawson** [comment]
This was fixed in todays release.
